// Shear, chapters 6-40: the Vector Swarm's own story. Its goal is the Bloom.
import { C, X } from './arc.js';

const GREEN_GATE = [{ faction: 'green', hq: false, ai: null, structures: [{ key: 'bastion', at: 'point:4' }, { key: 'beacon', at: 'point:4' }], squads: [{ key: 'wardens', at: 'point:4' }, { key: 'halo', at: 'point:4' }], points: [4] }];

export const BLUE_ARC = {
  goal: 'The Bloom',
  backstory: 'Before the fracture the Swarm was one thing. The Apex remembers being whole, and every Burrow the Swarm sinks is reaching for the seam where the one thing was cut: the Prime Vein. Seed the Vein and the Swarm divides through the whole Lattice at once, every shear-line a Hive, every crystal a triangle. The Foundry calls it a plague. The Collective calls it noise. The Apex calls it the Bloom, and it will go through both of them to reach it.',
  outcome: 'The Apex stands in the seam of the Prime Vein and divides. The Lattice is reforged in the shape that multiplies: one Swarm, everywhere, forever hungry.',
  acts: [
    { title: 'Act I · Awakening', from: 0 }, { title: 'Act II · The Basin', from: 5 }, { title: 'Act III · Shields', from: 10 },
    { title: 'Act IV · The Bleed', from: 15 }, { title: 'Act V · Scattered', from: 20 }, { title: 'Act VI · Pacts', from: 25 },
    { title: 'Act VII · Alone', from: 30 }, { title: 'Act VIII · The Bloom', from: 35 },
  ],
  chapters: [
    // ---- Act II · The Basin (6-10): the Foundry stands between the Hive and the ore it needs to grow.
    X('greywater', 2),
    X('drillfields', 2),
    C('Hungry Ground', 'crystal', 64, 3, 'protectStructure', { rival: 'red' },
      ['The Burrows in the dunes go deeper than any Foundry drill, and the deepest of them has found something: a hum under the crystal, faint, the note the Apex remembers from before the fracture. A Nest is growing over it, and it cannot move.', 'Foundry raiding columns are hunting the Burrows. The Apex has to keep the Nest alive for six minutes. Six minutes is a long time in the Swarm.'],
      'Protect the Nest at your forward point from Foundry raids, then destroy the raiders\' Watch Posts.',
      ['The Nest survives, scarred, and the raiders limp home to write it down.', 'The hum is louder now. It runs the length of the Salt Road, toward the Foundry\'s heartland, and the Apex intends to follow it.']),
    C('The Salt Road', 'frost', 64, 3, 'tugOfWar', { rival: 'red' },
      ['The Salt Road runs the length of Frostbite, outpost to outpost, from the Hive\'s forward camp to the Foundry\'s Works. The hum runs under it.', 'Every outpost the Swarm takes, the Hive sends more swarms up the road. The Apex does not hold ground. It flows.'],
      'Tug-of-war: push down the Salt Road outpost by outpost; each one taken brings reinforcements.',
      ['The Works at the end of the road burns. The Foundry retreats into its quarry.', 'A quarry is a hole with walls. The Swarm has never liked those, but the hum is loudest there.']),
    C('The Quarry', 'crystal', 64, 3, 'countdown', { rival: 'red', minutes: 9, waves: 6 },
      ['The Swarm has followed the hum into the crystal quarry, and the Foundry\'s whole army has followed the Swarm. The Hive is growing an Obelisk over the seam. It needs nine minutes.', 'Nine minutes of Foundry doctrine coming down the ramps.'],
      'Survive the countdown: hold the quarry for nine minutes until the Obelisk and its escort arrive, then break out.',
      ['The Obelisk walks out of the Hive on the ninth minute and the rim goes quiet, ramp by ramp.', 'The Basin is the Swarm\'s. The hum leads east now, across the ice, into ground the spheres have been watching from for months.']),
    // ---- Act III · Shields (11-15): the Collective has been watching the Basin war, and now the Swarm walks into its sight.
    C('The Watchers', 'frost', 64, 3, 'assault', { rival: 'green', ranks: [2, 3] },
      ['Beacons on every hill along the ice, and Bastions beside them. The Collective watched the whole Basin war from here and never fired a shot.', 'It fires now. The Swarm has never cared about being seen. Now it learns what the fog is for.'],
      'Assault the Beacon line on the ice and take the points it watched from.',
      ['The hills go blind one at a time and the Bastions fall silent for want of targets.', 'Behind the line the Foundry and the Collective are fighting on a frozen lake. Both of them are fed from one shore.']),
    X('glasslake', 3),
    C('Blind City', 'urban', 64, 4, 'assault', { rival: 'green', ranks: [2, 4, 5] },
      ['The Collective has seeded the Ruined City with Beacons. From each it sees ten blocks, and where it sees, its Bastions fire. The hum runs under the city too, and the Swarm has to cross it.', 'The Apex sends Kites over the roofs first. Beacons cannot see up.'],
      'Assault the Beacons and Bastions in the city and take the points they guarded.',
      ['The city goes blind, block by block. The Collective\'s beams fall silent for want of targets.', 'Then the sky lights up. Halos, and behind them a column of spheres crossing the dunes under them.']),
    X('halo', 4),
    C('The Sanctum', 'frost', 64, 4, 'commando', { rival: 'green', target: 'up' },
      ['The Collective\'s Sanctum harmonises every shield on the Glass Front, and its note is the opposite of the hum: it stills things. Where it plays, the Burrows go quiet.', 'The Apex goes in itself, with two squads, in the dark.'],
      'Commando: infiltrate the Collective rear with the Apex, destroy the Sanctum, and escape.',
      ['The Sanctum falls silent and every shield on the front flickers.', 'The hum comes back all at once, louder than it has ever been. The ice over the lake is melting from below.']),
    // ---- Act IV · The Bleed (16-20): the hum was the Vein rising. It eats the Hive first.
    X('bleed', 4),
    C('The Deep Burrow', 'crystal', 64, 4, 'protectStructure', { rival: 'green' },
      ['The Foundry says the Burrows woke the Bleed. The Apex has begun to think they were right, and does not care. A Spire at the forward point is listening to the seam, and what it hears is a direction.', 'The Collective wants the Spire dark. Kites are already in the air.'],
      'Protect the Spire at your forward point from Collective raids, then destroy the raiders\' Beacons.',
      ['The Spire survives and gives the Apex a heading: west, across the Ashfall.', 'The Collective, fleeing the Bleed, has decided the Ashfall is its only way out too.']),
    C('Ashfall Crossing', 'ashfall', 64, 5, 'countdown', { rival: 'green', minutes: 12, waves: 8 },
      ['The Swarm holds the Ashfall crossing alone. The Collective, fleeing the Bleed, is coming with everything it has left.', 'Twelve minutes until the Hive\'s new swarms reach the crossing.'],
      'Survive the countdown: hold the Ashfall crossing for twelve minutes until relief arrives, then counter-attack.',
      ['The relief swarms arrive on the twelfth minute and the crossing is a field of dark spheres.', 'The Foundry, walled up in the ruins since the Bleed, has started digging out on two roads at once.']),
    C('Divide', 'frost', 64, 5, 'multiFront', { rival: 'red' },
      ['The Foundry has dug out of the city on two roads, and the Swarm has bases on both. Neither base can help the other.', 'The Apex divides. It always could. It is, after all, what the Bloom will be.'],
      'Multi-front: hold both bases against Foundry pushes, then destroy the Foundry\'s forward base.',
      ['Both bases hold and the Foundry\'s forward base is rubble.', 'The winter is ending. The Foundry has one push left in it, and it is coming now.']),
    C('The Winter Push', 'urban', 80, 5, 'war', { rival: 'red' },
      ['The Foundry comes out of the ruins with everything it rebuilt in the winter: Bolts, Hammers, Breachers, Crushers, Mortars, and the Foreman.', 'The Hive meets it with everything it grew.'],
      'Full war against a living Foundry: destroy the Foundry in the ruins.',
      ['The Foundry cracks like a furnace door and the ruins go dark. The Foreman is not among the dead; he never is.', 'Then the Bleed comes for the ruins too, and the Hive with them.']),
    // ---- Act V · Scattered (21-25): the Bleed has eaten the Hive again. Bloom from what is left.
    C('Ashes', 'ashfall', 64, 5, 'commando', { rival: 'green', target: 'prod' },
      ['The Bleed has eaten the Hive, and the Apex walks out of the crystal with two squads and no home. The Collective has an Array in the ash, making Halos.', 'No home, no reinforcements. The Apex has never needed either.'],
      'Commando: with no base, infiltrate the Collective facility in the ash with the Apex, destroy the Array, and escape.',
      ['The Array burns in the ash and the Apex walks out of the smoke with both squads.', 'Somewhere in the craters, stranded swarms are still alive. The Apex can feel every one of them.']),
    X('scavenge', 5),
    C('The Obelisk Walks', 'frost', 64, 5, 'escort', { rival: 'red' },
      ['The scavenged Obelisk is the Swarm\'s only heavy weapon left in the world, and it is on the wrong side of the ice. The Foundry knows.', 'It walks. Everything else runs around it.'],
      'Escort duty: bring the Obelisk across the ice through Foundry ambushes to the far outpost.',
      ['The Obelisk arrives with Foundry shells still landing behind it.', 'The Foundry\'s new base is a fortress. It is fed by a road, and roads can be cut.']),
    C('Starve the Fortress', 'urban', 64, 5, 'interdiction', { rival: 'red' },
      ['The Foundry\'s new fortress in the ruins cannot be stormed: Bunkers on every approach, the Foreman inside. It is fed by convoys from the far veins.', 'The Swarm does not storm. It starves.'],
      'Supply interdiction: ambush the Foundry convoys and burn the rigs, then break the starving fortress.',
      ['The convoys stop coming and the fortress goes quiet, gun by gun.', 'The frozen river is the last line between the Swarm and the Foundry\'s heartland, and the hum runs straight across it.']),
    C('The Crossing', 'frost', 64, 6, 'tugOfWar', { rival: 'red' },
      ['The frozen river has five outposts along it, Foundry on every one. The Swarm takes them the way it takes everything: the next one, then the next.', 'Every outpost taken, the Hive sends more.'],
      'Tug-of-war: push across the frozen river outpost by outpost; each one taken brings reinforcements.',
      ['The far bank is Swarm. The Foundry\'s Works on it is glass.', 'An emissary is waiting on the far bank. It is a sphere, and it is not shooting.']),
    // ---- Act VI · Pacts (26-30): the Apex learns what an ally is, and what it is for.
    X('glasspact', 6),
    X('ironaccord', 6),
    X('shearpact', 6),
    X('betrayal', 6),
    C('The Reckoning', 'crystal', 80, 6, 'war', { rival: 'red' },
      ['The Foundry\'s betrayal has a price. The Swarm goes to collect it at the Foundry\'s dune fortress with everything it has.', 'There will be no more pacts. The Bloom does not share.'],
      'Full war: destroy the Foundry at its dune fortress.',
      ['The Foundry falls. The Foreman is not among the dead; he never is.', 'The Collective and the Foundry have both learned the same lesson about the Swarm. They will learn it together.']),
    // ---- Act VII · Alone (31-35): the other two peoples unite against the Bloom.
    C('Two Banners', 'verdant', 64, 7, 'twoBanners', { r1: 'red', r2: 'green' },
      ['Foundry Bunkers and Collective Bastions on the same ridge, under two banners. The old enemies have decided the Swarm is the newer problem.', 'The Apex finds this flattering.'],
      'Mixed garrison: clear a ridge held by both Foundry and Collective forces and take every point on it.',
      ['The ridge falls. The two garrisons never learned to fight together, only to die together.', 'Both strongholds are now sending everything they have, timed to arrive at once.']),
    C('Crossfire', 'urban', 80, 7, 'crossfire', { r1: 'red', r2: 'green', minutes: 9 },
      ['The coalition attacks from both corners of the city at once, waves timed to arrive together.', 'The Hive has three points, a Spire, and nine minutes to prove that a swarm surrounded is a swarm with more targets.'],
      'Two-front defence: hold three points for nine minutes against alternating Foundry and Collective waves.',
      ['The city is quiet and the streets are full of squares and spheres.', 'The Apex smells ore on the wind. Their economies are exposed.']),
    C('Scorched Vein', 'ashfall', 80, 7, 'raid', { rival: 'red', n: 4 },
      ['Foundry Drill Rigs and Collective Siphons share the lava fields now, each guarded by the other\'s turrets.', 'The Apex sends Kites and Wedges with one instruction: leave nothing that pumps ore.'],
      'Deep raid: destroy four coalition extractors on the lava fields without losing more than two squads.',
      ['The lava fields are dark. Two economies starve at once.', 'Only the Foundry\'s anvil stands between the Swarm and the Prime Vein.']),
    C('The Anvil', 'crystal', 80, 7, 'war', { rival: 'red', extraEnemies: GREEN_GATE },
      ['The Foundry has rebuilt in the canyons with Collective Bastions at its gates. It has learned everything. The Foreman calls the place the Anvil, and says the Lattice was forged on one like it.', 'So has the Apex learned. It does not care what the place is called.'],
      'Full war against a hardened Foundry with Collective support at its gates: destroy the Foundry.',
      ['The Foundry falls for the last time. The Collective garrison surrenders the gates.', 'Beyond the canyons the hum is no longer a hum. It is a chord, and the Apex has heard it before, from the inside.']),
    C('The Approaches', 'crystal', 64, 7, 'protectVip', { rival: 'green', ranks: [1, 2, 3] },
      ['The approaches to the Prime Vein are three points on a ridge, and the Collective holds them. The Apex must take them itself; the Swarm will not advance without it.', 'The Collective knows. Every Lens on the ridge is looking for the bright one.'],
      'Protect the VIP: keep the Apex alive while it leads the capture of the three approach points.',
      ['Three points, and the Apex still standing on the last of them.', 'The Vein is in sight. It glows, and it is calling.']),
    // ---- Act VIII · The Bloom (36-40): the end of the world, the Swarm's way.
    C('The Outer Ring', 'crystal', 80, 8, 'resourceRace', { rival: 'green', quota: 3000, minutes: 15 },
      ['The Outer Ring of the Prime Vein is the richest ore in the Lattice, and the Collective is drinking it as fast as the Swarm can eat it.', 'Whoever is larger when the Bleed returns wins the war before it starts, and the Bloom needs the Swarm larger than it has ever been.'],
      'Resource race: own the Outer Ring veins and stockpile three thousand ore before the Collective does.',
      ['The stockpile is full. The Hive is larger than it has ever been.', 'And the ground under it is glowing again.']),
    X('bleedreturns', 8),
    C('Last Obelisk', 'crystal', 80, 8, 'escort', { rival: 'green' },
      ['The last Obelisk in the world walks from the Nest to the centre, and both other peoples want it dead before it arrives.', 'It arrives, or the Swarm has no answer to what is waiting at the seam.'],
      'Escort duty: bring the last Obelisk to the centre through Collective ambushes.',
      ['The Obelisk stands at the centre of the world with the Swarm around it.', 'The other two armies are already there, in their corners, building.']),
    X('threecorners', 8),
    C('The Bloom', 'crystal', 80, 8, 'finale', {
      r1: 'red', r2: 'green',
      goal: [{ id: 'bloom', type: 'pop', text: 'Bloom: field an army of 30 population', n: 30 }, { id: 'seed', type: 'heroAt', text: 'Bring the Apex to the seam of the Prime Vein', at: 'center', radius: 5 }],
      goalIntro: 'Both of them are broken. The seam is open. Bloom, and bring the Apex to it.',
    },
      ['The Prime Vein lies open under the dunes, and around it, in three corners of the world, three peoples have built everything they have left. The Foundry wants to forge it. The Collective wants to still it.', 'The Swarm wants to be it. The Apex has waited its whole existence for this, and it will have to go through both of them.'],
      'The finale: destroy both the Foundry and the Core, then bloom and bring the Apex to the seam.',
      ['The Foundry falls. The Core falls. The Apex walks into the seam of the Prime Vein and divides, and divides, and divides.', 'The Lattice is reforged in the shape that multiplies. One Swarm, everywhere, forever hungry. Campaign complete.']),
  ],
};
