// Campaign: Shear (Vector Swarm). Twenty chapters in four acts.
import { garrison, war, obj, stage, wave, fortified } from './common.js';

const F = 'blue';
export const BLUE = {
  faction: F, title: 'Shear', tagline: 'The Swarm wakes. The Swarm divides. The Swarm takes.',
  intro: 'The Hive slept through the long dark, its triangles folded flat against the shear-line. Now the ore hum has returned and the Apex stirs. The Swarm does not plan. It multiplies, it moves, and it arrives from the side nobody is watching.',
  acts: [{ title: 'Act I · First Bloom', from: 0 }, { title: 'Act II · Iron Country', from: 5 }, { title: 'Act III · The Green Tide', from: 10 }, { title: 'Act IV · The Coalition', from: 15 }, { title: 'Finale', from: 19 }],
  chapters: [
    // ---------------- ACT I: lessons
    {
      key: 'blue-1', title: 'First Bloom', theme: 'verdant', size: 48, seed: 'shear-1',
      story: ['The Hive cracks open in the Verdant Basin. Around it, rusting Foundry outposts still guard the old ore veins, abandoned by a garrison that never expected the shear-line to wake.', 'You are the first thought of the Apex. Bloom. Feed. Spread.'],
      briefing: 'Learn the basics: train Dart Swarms, mine ore, and capture your first strategic point.',
      epilogue: ['The first point falls in seconds. The Foundry garrison did not even turn around. The Hive tastes ore and starts to divide faster.', 'Scouts report armour moving on the river road. The Foundry has noticed.'],
      player: { faction: F, ore: 300, flux: 60, units: ['darts'], buildings: ['lode'] },
      enemy: garrison('red', { squads: [{ key: 'bolts', at: 'point:2', hp: 0.7 }], points: [2] }),
      stages: [
        stage([obj('train', 'train', 'Train 2 Dart Swarms at the Hive', { key: 'darts', n: 2, hint: 'Tap the Hive, then tap Dart Swarm.' })]),
        stage([obj('lode', 'build', 'Build a Lode Burrow on an ore vein', { key: 'lode', n: 1, hint: 'Tap Build, choose Lode Burrow, tap the glowing vein.' })], 'Swarms need ore. Burrow into the vein beside the Hive.'),
        stage([obj('cap', 'capture', 'Capture the nearest strategic point', { rank: 0, hint: 'Select a swarm and tap the flag marker.' })], 'Flux comes only from strategic points. Stand on one to claim it.'),
        stage([obj('kill', 'kill', 'Destroy the Bolt Squad guarding the second point', { n: 1, hint: 'Long-press the ground near them to attack-move.' }), obj('cap2', 'capture', 'Capture the second point', { rank: 2 })], 'A Foundry squad holds the next point. Eight blades beat four rifles up close.'),
      ],
      hints: [{ at: 'start', text: 'Drag to pan, pinch to zoom. Your Hive is selected: tap Dart Swarm twice.' }, { at: 'stage:3', text: 'Darts are melee. Charge in together; do not trickle.' }],
    },
    {
      key: 'blue-2', title: 'Needle and Thread', theme: 'verdant', size: 48, seed: 'shear-2',
      story: ['A Crusher Tank grinds down the river road with Bolt Squads in its shadow. Darts shatter against its plating; blades cannot bite iron.', 'The Hive answers by growing something new: long, hollow Needles that punch through armour. And it learns the other lesson of the basin: the boulders and brush are not scenery. They are shields.'],
      briefing: 'Counters and cover: build Needle Squads to kill armour, fight from cover, and reinforce a bled squad.',
      epilogue: ['The tank dies with Needles still bristling from its hull. Its escort breaks and runs for the frost line.', 'The Apex follows the retreat with a thousand eyes. Where they run, the Foundry is thin.'],
      player: { faction: F, ore: 420, flux: 80, units: ['darts', 'needles'], buildings: ['lode', 'thorn'], squads: [{ key: 'darts', at: [3, 4] }] },
      enemy: garrison('red', { squads: [{ key: 'crusher', at: 'point:3' }, { key: 'bolts', at: 'point:3', n: 2 }, { key: 'bolts', at: 'point:1' }], points: [1, 3] }),
      waves: [wave(150, [{ key: 'bolts', n: 2 }], { from: 'point:3', target: 'point:0', text: 'Foundry infantry is moving on your point.' })],
      stages: [
        stage([obj('needles', 'train', 'Train 2 Needle Squads', { key: 'needles', n: 2 }), obj('lode', 'build', 'Claim both ore veins near the Hive', { key: 'lode', n: 2, optional: true })]),
        stage([obj('cap', 'capture', 'Capture the nearest point', { rank: 0 }), obj('cover', 'cover', 'Take 8 hits while in cover', { n: 8, hint: 'Park a squad beside a boulder facing the enemy, or inside brush.' }), obj('reinf', 'reinforce', 'Reinforce a damaged squad twice', { n: 2 })], 'Take the closest point, and fight from behind rocks and brush. The shield icon over a squad means the cover is working.'),
        stage([obj('tank', 'kill', 'Destroy the Crusher Tank', { key: 'crusher', n: 1 }), obj('cap3', 'capture', 'Capture the point it was guarding', { rank: 3 })], 'The tank sits at the far point. Needles first, Darts on its escort.'),
      ],
      hints: [{ at: 'start', text: 'Needle Squads deal anti-armour damage: 1.5× against vehicles, weak in melee.' }, { at: 'time:150', text: 'Enemy infantry inbound. Hold your point from cover.' }],
    },
    {
      key: 'blue-3', title: 'The Long Way Round', theme: 'frost', size: 64, seed: 'shear-3',
      story: ['The retreat leads into Frostbite, where the Foundry has dug Hammer Teams into the passes. A Hammer Team pins anything in front of it; squads that charge it head-on break before they arrive.', 'The Hive grows a Nest, and from the Nest come Wedges: the fastest thing on the ice. Wedges do not go through. They go around.'],
      briefing: 'Flanking and morale: build the Nest, raise Wedge Raiders, hit the gun teams from behind and break them.',
      epilogue: ['Three Hammer Teams die facing the wrong way. The passes belong to the Swarm.', 'Beyond the ice, the sky is orange. The Foundry has been drilling in the Ashfall for years, and its refineries are unguarded from above.'],
      player: { faction: F, ore: 500, flux: 120, units: ['darts', 'needles', 'wedges'], buildings: ['lode', 'nest', 'thorn', 'claim'], squads: [{ key: 'darts', at: [3, 4] }, { key: 'needles', at: [5, 2] }] },
      enemy: garrison('red', { squads: [{ key: 'hammers', at: 'point:1', order: 'hold' }, { key: 'hammers', at: 'point:3', order: 'hold' }, { key: 'hammers', at: 'point:4', order: 'hold' }, { key: 'bolts', at: 'point:3' }, { key: 'bolts', at: 'point:4' }], points: [1, 3, 4], structures: [{ key: 'post', at: 'point:3' }] }),
      stages: [
        stage([obj('nest', 'build', 'Build a Nest', { key: 'nest', n: 1 }), obj('wedges', 'train', 'Train 2 Wedge Raiders', { key: 'wedges', n: 2 })]),
        stage([obj('flank', 'flank', 'Land 12 flanking hits', { n: 12, hint: 'A squad is flanked when hit from more than 110° behind its facing.' }), obj('broken', 'broken', 'Break 2 enemy squads', { n: 2 })], 'Attacks from behind deal extra damage and shred morale. Wedges double the bonus. Circle wide, then strike.'),
        stage([obj('post', 'destroy', 'Destroy the Watch Post', { key: 'post', n: 1 }), obj('cap', 'capture', 'Hold 4 strategic points', { n: 4 })], 'Now roll up the passes. The Watch Post must fall before its point can be taken.'),
      ],
      hints: [{ at: 'start', text: 'Hammer Teams must set up to fire and have a narrow arc. Never approach one from the front.' }, { at: 'stage:2', text: 'Broken squads fight at a third strength and take 50% more damage. Finish them.' }],
    },
    {
      key: 'blue-4', title: 'Wings over Ash', theme: 'ashfall', size: 64, seed: 'shear-4',
      story: ['The Ashfall is Foundry country: drill rigs on every vein, bunkers on every road, lava between. On the ground the Swarm would be ground down.', 'So the Hive raises a Spire, and from the Spire come Kites: hovering triangles that ignore lava, walls and roads alike. An economy that cannot be defended is not an economy.'],
      briefing: 'Harassment: build a Spire, raise Kites, burn the Foundry drill rigs, and starve a living opponent while you hold the points.',
      epilogue: ['Rig after rig goes dark. With no ore the Foundry stops building, then stops fighting, then simply stops.', 'The Apex has watched long enough. It will lead the next assault itself.'],
      player: { faction: F, ore: 550, flux: 150, units: ['darts', 'needles', 'wedges', 'kites'], buildings: ['lode', 'nest', 'spire', 'thorn', 'claim'] },
      enemy: war('red', 'easy', { incomeMult: 0.9, structures: [{ key: 'drill', at: 'ore:6' }, { key: 'drill', at: 'ore:7' }, { key: 'drill', at: 'ore:4' }, { key: 'bunker', at: [-3, 3] }, { key: 'works', at: [4, -2] }], squads: [{ key: 'bolts', at: [0, 5] }, { key: 'hammers', at: [-4, 0] }] }),
      stages: [
        stage([obj('spire', 'build', 'Build a Spire', { key: 'spire', n: 1 }), obj('kites', 'train', 'Train 2 Kite Wings', { key: 'kites', n: 2 })]),
        stage([obj('rigs', 'destroy', 'Destroy 3 Drill Rigs', { key: 'drill', n: 3 }), obj('hold', 'hold', 'Hold 4 points for 90 seconds', { n: 4, seconds: 90 })], 'Kites fly. Cross the lava, hit the drill rigs, leave before the bunkers turn.'),
      ],
      hints: [{ at: 'start', text: 'The Foundry here is alive and will attack. Claim your veins and points early.' }, { at: 'stage:1', text: 'Kites are vehicles: anti-armour and energy hurt them. Avoid Needle-type fire and turrets.' }],
    },
    {
      key: 'blue-5', title: 'Apex', theme: 'urban', size: 64, seed: 'shear-5',
      story: ['The Ruined City is where the Foundry makes its stand: walls, bunkers, and everything it has left thrown down the streets in waves.', 'The Apex takes the field. Where it moves the Swarm moves faster and never breaks; attached to a squad it becomes the point of a spear. But even the Apex knows when to pull back and bloom again.'],
      briefing: 'Hero and morale: train the Apex, attach it to a squad, retreat and rally a broken squad, and survive the Foundry counter-offensive.',
      epilogue: ['The last wave dies in the streets. Somewhere behind the walls the Foreman calls the retreat, and the Foundry pulls back along the river toward its heartland.', 'The Hive feels the Prime Vein now, faintly, like a heartbeat under the whole Lattice.'],
      player: { faction: F, ore: 600, flux: 200, squads: [{ key: 'darts', at: [3, 4] }, { key: 'needles', at: [5, 2] }, { key: 'wedges', at: [2, 6] }], structures: [{ key: 'nest', at: [-4, 3] }] },
      enemy: garrison('red', { structures: [{ key: 'bunker', at: 'point:3' }, { key: 'post', at: 'point:3' }], squads: [{ key: 'bolts', at: 'point:1' }], points: [1, 3] }),
      waves: [wave(90, [{ key: 'bolts', n: 2 }], { text: 'Foundry wave one. Hold the streets.' }), wave(180, [{ key: 'bolts', n: 2 }, { key: 'hammers', n: 1 }], { text: 'Wave two, with a gun team. Flank it.' }), wave(270, [{ key: 'breachers', n: 1 }, { key: 'bolts', n: 2 }], { text: 'Wave three: Breachers. Keep the Apex close.' }), wave(360, [{ key: 'crusher', n: 1 }, { key: 'bolts', n: 2 }, { key: 'hammers', n: 1 }], { text: 'Final wave: armour. Needles forward.' })],
      stages: [
        stage([obj('hero', 'hero', 'Train the Apex at the Hive'), obj('attach', 'attach', 'Attach the Apex to a squad', { hint: 'Select the Apex, tap Attach, then tap a squad.' })]),
        stage([obj('retreat', 'retreat', 'Order a retreat', { n: 1 }), obj('rally', 'rally', 'Rally a broken squad (let its morale recover)', { n: 1 }), obj('survive', 'survive', 'Survive the Foundry offensive (7 minutes)', { seconds: 420 })], 'Waves are coming. When a squad breaks, Retreat it: it sprints home, recovers, and comes back.'),
        stage([obj('bunker', 'destroy', 'Destroy the Bunker', { key: 'bunker', n: 1 }), obj('cap', 'capture', 'Capture the fortified point', { rank: 3 })], 'The waves are spent. Take their forward position.'),
      ],
      hints: [{ at: 'start', text: 'The Apex aura gives nearby squads speed and morale. Keep the army inside it.' }],
    },
    // ---------------- ACT II: Iron Country
    {
      key: 'blue-6', title: 'Riverline', theme: 'verdant', size: 64, seed: 'shear-6',
      story: ['The Foundry falls back across the basin river and digs in on the far bank. The fords are the only way over, and every ford has a Bunker looking at it.', 'The Hive does not need to cross yet. It needs the near bank, every point on it, and enough Thorns to make the Foundry stop trying.'],
      briefing: 'Defence: fortify the near bank with Thorns and Claim Spikes, and hold three points against repeated crossings.',
      epilogue: ['Three crossings, three retreats. The river runs with iron filings.', 'With the bank secure, the Hive turns to the drill fields the Foundry left behind it.'],
      player: { faction: F, ore: 520, flux: 160, squads: [{ key: 'darts', at: [3, 4] }, { key: 'needles', at: [5, 2] }] },
      enemy: garrison('red', { structures: [{ key: 'bunker', at: 'point:4' }, { key: 'bunker', at: 'point:5' }, { key: 'post', at: 'point:5' }], squads: [{ key: 'bolts', at: 'point:4' }, { key: 'hammers', at: 'point:5', order: 'hold' }], points: [4, 5, 6] }),
      waves: [wave(120, [{ key: 'bolts', n: 2 }], { from: 'point:4', target: 'point:0', text: 'A crossing at the near ford.' }), wave(240, [{ key: 'bolts', n: 2 }, { key: 'breachers', n: 1 }], { from: 'point:5', target: 'point:2', text: 'Breachers at the far ford. They will go for your Spikes.' }), wave(360, [{ key: 'crusher', n: 1 }, { key: 'bolts', n: 2 }], { from: 'point:4', target: 'point:0', text: 'Armour on the ford. Needles to the bank.' })],
      stages: [
        stage([obj('cap', 'capture', 'Hold 3 strategic points', { n: 3 }), obj('claim', 'build', 'Fortify 2 points with Claim Spikes', { key: 'claim', n: 2 }), obj('thorn', 'build', 'Build 2 Thorns', { key: 'thorn', n: 2 })]),
        stage([obj('hold', 'hold', 'Hold 3 points for 4 minutes', { n: 3, seconds: 240 }), obj('loss', 'loseMax', 'Lose no more than 2 squads', { n: 2, optional: true })], 'Now hold. Thorns at the fords, Needles behind them, Darts to mop up.'),
      ],
      hints: [{ at: 'start', text: 'Claim Spikes extend your build radius: a Thorn beside a Spike holds a point on its own.' }],
    },
    {
      key: 'blue-7', title: 'Drill Fields', theme: 'ashfall', size: 64, seed: 'shear-7',
      story: ['The Ashfall drill fields, again, but this time the Foundry is not surprised. It has a Works running and it is building.', 'The Apex does not intend to fight the army the Foundry is building. It intends to have more ore than the Foundry ever will, and let the numbers argue.'],
      briefing: 'Economy race: claim four ore veins and hold four points before the Foundry does, then break its Works.',
      epilogue: ['The Foundry Works falls silent for want of ore, then falls.', 'The Apex has learned patience. It does not enjoy it.'],
      player: { faction: F, ore: 500, flux: 120 },
      enemy: war('red', 'normal', { incomeMult: 0.95, structures: [{ key: 'works', at: [4, -2] }, { key: 'drill', at: 'ore:6' }, { key: 'drill', at: 'ore:7' }, { key: 'bunker', at: [-3, 3] }], squads: [{ key: 'bolts', at: [0, 5] }] }),
      timeLimit: 900,
      stages: [
        stage([obj('lode', 'build', 'Own 4 Lode Burrows', { key: 'lode', n: 4 }), obj('cap', 'capture', 'Hold 4 strategic points', { n: 4 })], 'Fifteen minutes. Expand faster than the Foundry.'),
        stage([obj('works', 'destroy', 'Destroy the Iron Works', { key: 'works', n: 1 })], 'Now spend it. Wedges around the flank, Darts down the middle.'),
      ],
      hints: [{ at: 'start', text: 'Contested veins in the middle are worth a fight. Take them with Wedges and Spike the nearest point.' }],
    },
    {
      key: 'blue-8', title: 'The Quarry', theme: 'crystal', size: 64, seed: 'shear-8',
      story: ['The Foundry has turned a crystal quarry into a fortress: Bunkers on every ridge, a Watch Post on every point, and canyon walls between. Nothing on foot gets close.', 'The Spire grows the first Obelisk. It walks out of the Hive slowly, and the Bunkers watch it come, out of range, and stay out of range.'],
      briefing: 'Siege: field an Obelisk and use its reach to dismantle a fortified position without charging the guns.',
      epilogue: ['The quarry is craters and glass. Nothing shot back at the end.', 'The Foundry has one stronghold left in the west. The Swarm has one road to it.'],
      player: { faction: F, ore: 700, flux: 260, structures: [{ key: 'nest', at: [-4, 3] }, { key: 'spire', at: [4, -3] }], squads: [{ key: 'darts', at: [3, 4], n: 2 }, { key: 'needles', at: [5, 2] }] },
      enemy: garrison('red', { structures: [{ key: 'bunker', at: 'point:3' }, { key: 'bunker', at: 'point:4' }, { key: 'bunker', at: 'point:5' }, { key: 'post', at: 'point:3' }, { key: 'post', at: 'point:4' }, { key: 'post', at: 'point:5' }, { key: 'drill', at: 'ore:5' }], squads: [{ key: 'hammers', at: 'point:3', order: 'hold' }, { key: 'bolts', at: 'point:4' }, { key: 'mortar', at: 'point:5', order: 'hold' }], points: [3, 4, 5] }),
      stages: [
        stage([obj('obelisk', 'train', 'Field an Obelisk', { key: 'obelisk', n: 1 })]),
        stage([obj('bunkers', 'destroy', 'Destroy 3 Bunkers', { key: 'bunker', n: 3 }), obj('posts', 'destroy', 'Destroy 3 Watch Posts', { key: 'post', n: 3 })], 'Walk the Obelisk to the edge of each Bunker\'s range and let it work. Screen it against the mortar crew.'),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 })]),
      ],
      hints: [{ at: 'start', text: 'The Mortar Block outranges your Obelisk\'s escort but not the Obelisk. Send Wedges for the crew.' }],
    },
    {
      key: 'blue-9', title: 'Salt Road', theme: 'frost', size: 64, seed: 'shear-9',
      story: ['The salt road to the Foundry heartland runs between two ice lakes, and the Foundry has bases on both. Whichever way the Swarm faces, the other side hits its back.', 'The Apex has one answer to being surrounded: be somewhere else. Retreat, rally, return.'],
      briefing: 'Two fronts: survive alternating attacks from two directions, keeping your squads alive through retreat and rally.',
      epilogue: ['Both bases spend themselves on a swarm that keeps disappearing and coming back whole.', 'The road is open. At its end stands the Foundry itself.'],
      player: { faction: F, ore: 650, flux: 220, structures: [{ key: 'nest', at: [-4, 3] }], squads: [{ key: 'darts', at: [3, 4], n: 2 }, { key: 'needles', at: [5, 2] }, { key: 'apex', at: [2, 2] }] },
      enemy: garrison('red', { structures: [{ key: 'bunker', at: 'point:4' }, { key: 'bunker', at: 'point:5' }], squads: [{ key: 'bolts', at: 'point:4' }, { key: 'bolts', at: 'point:5' }], points: [4, 5] }),
      waves: [wave(80, [{ key: 'bolts', n: 2 }], { from: 'point:4', text: 'West lake: infantry.' }), wave(170, [{ key: 'breachers', n: 2 }], { from: 'point:5', text: 'East lake: Breachers.' }), wave(260, [{ key: 'bolts', n: 2 }, { key: 'hammers', n: 1 }], { from: 'point:4', text: 'West lake again, with a gun team.' }), wave(350, [{ key: 'crusher', n: 1 }, { key: 'bolts', n: 1 }], { from: 'point:5', text: 'East lake: a tank.' }), wave(440, [{ key: 'bolts', n: 3 }, { key: 'breachers', n: 1 }], { from: 'point:4', text: 'Everything they have left.' })],
      stages: [
        stage([obj('survive', 'survive', 'Survive 9 minutes of attacks', { seconds: 540 }), obj('retreat', 'retreat', 'Retreat 3 times', { n: 3 }), obj('rally', 'rally', 'Rally 2 broken squads', { n: 2 }), obj('loss', 'loseMax', 'Lose no more than 3 squads', { n: 3, optional: true })]),
        stage([obj('bunkers', 'destroy', 'Destroy both Bunkers', { key: 'bunker', n: 2 }), obj('cap', 'capture', 'Hold 5 points', { n: 5 })], 'Their waves are spent. Take both lakes.'),
      ],
      hints: [{ at: 'start', text: 'A retreating squad sprints and recovers morale at home. Use it early, not when the squad is already dead.' }],
    },
    {
      key: 'blue-10', title: 'Foundry\'s Fall', theme: 'urban', size: 80, seed: 'shear-10',
      story: ['The Foundry heartland: a city of walls with the Foundry itself at its centre, ringed by Bunkers and everything the Foreman has learned about the Swarm.', 'This is not a raid. The Hive brings Darts, Needles, Wedges, Kites, the Apex and an Obelisk, and it does not intend to leave a wall standing.'],
      briefing: 'Full war against a living Foundry: out-produce it, break the walls, and destroy the Foundry.',
      epilogue: ['The Foundry cracks like a furnace door and the city goes dark. The Foreman is not among the dead; he never is.', 'From the east, over the glass lakes, a new hum: the Aegis Collective has woken, and it has been watching the whole war.'],
      player: { faction: F, ore: 600, flux: 220 },
      enemy: fortified('red', 'normal', { structures: [{ key: 'post', at: 'point:5' }, { key: 'armory', at: [-5, -3] }] }),
      stages: [
        stage([obj('econ', 'capture', 'Hold 3 strategic points', { n: 3 }), obj('obelisk', 'train', 'Field an Obelisk', { key: 'obelisk', n: 1 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Foundry'), obj('loss', 'loseMax', 'Lose no more than 8 squads', { n: 8, optional: true })], 'The Obelisk outranges bunkers. Screen it with Darts and let it walk.'),
      ],
      hints: [{ at: 'start', text: 'The Foundry will not wait. Two Thorns and a Needle Squad at home while you expand.' }],
    },
    // ---------------- ACT III: The Green Tide
    {
      key: 'blue-11', title: 'The Glass Lake', theme: 'frost', size: 64, seed: 'shear-11',
      story: ['The Collective\'s first squads stand on the frozen lake behind shields that swallow Dart blades and Needle spikes alike. They do not advance. They simply do not die.', 'The Apex studies them for an hour and finds the rule: a shield that is left alone comes back. A shield that is never left alone does not.'],
      briefing: 'Shields: learn to focus fire and never let a Collective squad rest. Kill the Warden Cells and Lens Teams on the lake.',
      epilogue: ['Four Wardens and two Lenses lie on the ice, shields dark. The Collective withdraws to compute.', 'It will be back. The Apex intends to be somewhere it does not expect.'],
      player: { faction: F, ore: 600, flux: 200, squads: [{ key: 'darts', at: [3, 4], n: 2 }, { key: 'needles', at: [5, 2] }, { key: 'wedges', at: [2, 6] }] },
      enemy: garrison('green', { squads: [{ key: 'wardens', at: 'point:2', n: 2 }, { key: 'lenses', at: 'point:2' }, { key: 'wardens', at: 'point:4', n: 2 }, { key: 'lenses', at: 'point:4' }], points: [2, 4] }),
      stages: [
        stage([obj('wardens', 'kill', 'Destroy 4 Warden Cells', { key: 'wardens', n: 4 }), obj('lenses', 'kill', 'Destroy 2 Lens Teams', { key: 'lenses', n: 2 }), obj('flank', 'flank', 'Land 10 flanking hits', { n: 10 })], 'Shields recharge after three seconds without damage. Commit everything to one squad at a time.'),
        stage([obj('cap', 'capture', 'Hold 4 points', { n: 4 })]),
      ],
      hints: [{ at: 'start', text: 'Lens Teams outrange everything you have. Wedges around the back, before anything else.' }],
    },
    {
      key: 'blue-12', title: 'Halo', theme: 'crystal', size: 64, seed: 'shear-12',
      story: ['A Collective column crosses the dunes under a hovering ring. Every shield near it refills as fast as the Swarm can drain it.', 'Kill the ring, the Apex decides, and the rest are just spheres.'],
      briefing: 'Target priority: kill the Halos protecting a Collective column, then finish the column.',
      epilogue: ['Two rings fall from the sky. Without them the column is a slow, expensive rout.', 'The Collective has begun planting Beacons on every point it can reach. It is trying to see.'],
      player: { faction: F, ore: 650, flux: 220, structures: [{ key: 'nest', at: [-4, 3] }, { key: 'spire', at: [4, -3] }], squads: [{ key: 'needles', at: [3, 4], n: 2 }, { key: 'darts', at: [5, 2] }] },
      enemy: war('green', 'passive', { incomeMult: 0.9, structures: [{ key: 'array', at: [4, -2] }, { key: 'siphon', at: 'ore:6' }, { key: 'siphon', at: 'ore:7' }], squads: [{ key: 'halo', at: 'point:4' }, { key: 'halo', at: 'point:5' }, { key: 'wardens', at: 'point:4', n: 2 }, { key: 'pulsers', at: 'point:5' }] }),
      stages: [
        stage([obj('halos', 'kill', 'Destroy 2 Halos', { key: 'halo', n: 2, hint: 'Needles and Kites: the Halo is a vehicle.' }), obj('kill', 'kill', 'Destroy 6 Collective squads', { n: 6 })]),
        stage([obj('cap', 'capture', 'Hold 4 points', { n: 4 }), obj('array', 'destroy', 'Destroy the Array', { key: 'array', n: 1, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Kites can reach a Halo over terrain the escort cannot cross. Strike and leave.' }],
    },
    {
      key: 'blue-13', title: 'Blind Spot', theme: 'urban', size: 64, seed: 'shear-13',
      story: ['The Collective has seeded the Ruined City with Beacons. From each, it sees ten blocks in every direction, and where it sees, its Bastions fire.', 'The Swarm has never cared about being seen. Now it learns what the fog is for.'],
      briefing: 'Vision: destroy the Beacons and Bastions that let the Collective see the city, then take its points in the dark.',
      epilogue: ['The city goes blind, block by block. The Collective\'s beams fall silent for want of targets.', 'Then the sky lights up: Nova Spheres, firing from beyond sight.'],
      player: { faction: F, ore: 600, flux: 200, squads: [{ key: 'wedges', at: [3, 4], n: 2 }, { key: 'darts', at: [5, 2] }, { key: 'kites', at: [2, 6] }] },
      enemy: garrison('green', { structures: [{ key: 'beacon', at: 'point:2' }, { key: 'beacon', at: 'point:4' }, { key: 'beacon', at: 'point:5' }, { key: 'bastion', at: 'point:4' }, { key: 'bastion', at: 'point:5' }], squads: [{ key: 'wardens', at: 'point:4' }, { key: 'lenses', at: 'point:5' }], points: [2, 4, 5] }),
      stages: [
        stage([obj('beacons', 'destroy', 'Destroy 3 Beacons', { key: 'beacon', n: 3 }), obj('bastions', 'destroy', 'Destroy 2 Bastions', { key: 'bastion', n: 2 })], 'Bastions outrange you on open ground. Come at them through the blocks the Beacons cannot see.'),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 }), obj('loss', 'loseMax', 'Lose no more than 3 squads', { n: 3, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Kites can kill a Beacon from over a wall before the Bastion turns.' }],
    },
    {
      key: 'blue-14', title: 'Nova Rain', theme: 'ashfall', size: 64, seed: 'shear-14',
      story: ['Nova Spheres roll across the lava plain, each one a small star that leaves craters where swarms used to be. They outrange the Obelisk. They outrange everything.', 'But they are slow, and the ground between shells is a place the Swarm knows how to cross.'],
      briefing: 'Artillery: survive a Nova bombardment, then run the guns down with Wedges and Kites before the escort can turn.',
      epilogue: ['The last Sphere goes dark with Wedges on its shell. The plain is craters from edge to edge.', 'One thing remains: the Core itself.'],
      player: { faction: F, ore: 700, flux: 260, structures: [{ key: 'nest', at: [-4, 3] }, { key: 'spire', at: [4, -3] }], squads: [{ key: 'wedges', at: [3, 4], n: 2 }, { key: 'kites', at: [5, 2] }, { key: 'darts', at: [2, 6], n: 2 }] },
      enemy: garrison('green', { structures: [{ key: 'bastion', at: 'point:4' }], squads: [{ key: 'nova', at: 'point:4', order: 'hold' }, { key: 'nova', at: 'point:5', order: 'hold' }, { key: 'wardens', at: 'point:4' }, { key: 'pulsers', at: 'point:5' }], points: [4, 5] }),
      waves: [wave(90, [{ key: 'nova', n: 1 }, { key: 'wardens', n: 1 }], { from: 'point:5', target: 'point:0', text: 'A Nova is rolling toward your point.' }), wave(240, [{ key: 'halo', n: 1 }, { key: 'wardens', n: 2 }], { from: 'point:4', target: 'point:2', text: 'A shielded column with a Halo.' })],
      stages: [
        stage([obj('novas', 'kill', 'Destroy 3 Nova Spheres', { key: 'nova', n: 3, hint: 'Get inside their minimum range. Wedges and Kites.' }), obj('survive', 'survive', 'Survive the bombardment (6 minutes)', { seconds: 360 })]),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 })]),
      ],
      hints: [{ at: 'start', text: 'Nova shells land where you were. Keep squads moving, and never clump.' }],
    },
    {
      key: 'blue-15', title: 'The Core', theme: 'frost', size: 80, seed: 'shear-15',
      story: ['The Core sits on the ice inside a shield that could stop the sky, ringed by Bastions and Halos, with the Oracle somewhere inside computing the Swarm\'s every move.', 'The Apex intends to make more moves than can be computed.'],
      briefing: 'Full war against a living Collective: destroy the Core.',
      epilogue: ['The shield fails. The Core cracks open and the Oracle\'s light goes out across the ice.', 'For a moment the Lattice is quiet. Then the Foundry and the Collective, both broken, find each other, and find a common enemy.'],
      player: { faction: F, ore: 650, flux: 240 },
      enemy: fortified('green', 'normal', { incomeMult: 1.15, structures: [{ key: 'beacon', at: 'point:5' }, { key: 'sanctum', at: [-5, -3] }] }),
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('kites', 'train', 'Field 2 Kite Wings', { key: 'kites', n: 2 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Core'), obj('loss', 'loseMax', 'Lose no more than 10 squads', { n: 10, optional: true })], 'Kites on the Siphons, Wedges on the Lenses, and the Obelisk for the Core.'),
      ],
      hints: [{ at: 'start', text: 'Energy weapons eat Kites and Obelisks. Let Darts draw the fire.' }],
    },
    // ---------------- ACT IV: The Coalition
    {
      key: 'blue-16', title: 'Two Banners', theme: 'verdant', size: 64, seed: 'shear-16',
      story: ['Foundry Bunkers and Collective Bastions on the same ridge, under two banners. The old enemies have decided the Swarm is the newer problem.', 'The Apex finds this flattering, and inconvenient.'],
      briefing: 'Mixed garrison: clear a ridge held by both Foundry and Collective forces and take every point on it.',
      epilogue: ['The ridge falls. The two garrisons never learned to fight together, only to die together.', 'Both remaining strongholds are now sending everything they have.'],
      player: { faction: F, ore: 650, flux: 240, structures: [{ key: 'nest', at: [-4, 3] }], squads: [{ key: 'darts', at: [3, 4], n: 2 }, { key: 'needles', at: [5, 2] }, { key: 'wedges', at: [2, 6] }] },
      enemies: [garrison('red', { structures: [{ key: 'bunker', at: 'point:2' }, { key: 'post', at: 'point:2' }], squads: [{ key: 'bolts', at: 'point:2' }, { key: 'hammers', at: 'point:2', order: 'hold' }], points: [2] }), garrison('green', { structures: [{ key: 'bastion', at: 'point:4' }, { key: 'beacon', at: 'point:4' }], squads: [{ key: 'wardens', at: 'point:4' }, { key: 'lenses', at: 'point:4' }], points: [4] })],
      stages: [
        stage([obj('kill', 'kill', 'Destroy 4 enemy squads', { n: 4 }), obj('posts', 'destroy', 'Destroy the Watch Post and the Beacon', { n: 2 })]),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 })]),
      ],
      hints: [{ at: 'start', text: 'Two enemies, two answers: melee for the Foundry line, focus fire for the shields.' }],
    },
    {
      key: 'blue-17', title: 'Crossfire', theme: 'urban', size: 80, seed: 'shear-17',
      story: ['The coalition attacks from both corners of the city at once, in waves timed to arrive together.', 'The Hive has three points, a Spire, and eight minutes to prove that a swarm surrounded is a swarm with more targets.'],
      briefing: 'Two-front defence: hold three points for eight minutes against alternating Foundry and Collective waves.',
      epilogue: ['The city is quiet and the streets are full of squares and spheres.', 'The Apex smells ore on the wind. Their economies are exposed.'],
      player: { faction: F, ore: 750, flux: 300, structures: [{ key: 'nest', at: [-4, 3] }, { key: 'spire', at: [4, -3] }, { key: 'thorn', at: [6, 1] }], squads: [{ key: 'darts', at: [3, 4], n: 2 }, { key: 'needles', at: [5, 2], n: 2 }, { key: 'apex', at: [2, 2] }], points: [0, 1, 2] },
      enemies: [garrison('red', { points: [4] }), garrison('green', { points: [5] })],
      waves: [wave(60, [{ key: 'bolts', n: 2 }], { owner: 1, text: 'Foundry infantry from the north.' }), wave(120, [{ key: 'wardens', n: 2 }], { owner: 2, text: 'Collective Wardens from the south.' }), wave(200, [{ key: 'crusher', n: 1 }, { key: 'bolts', n: 1 }], { owner: 1, text: 'Foundry armour.' }), wave(280, [{ key: 'pulsers', n: 2 }, { key: 'lenses', n: 1 }], { owner: 2, text: 'Pulse Rings and a Lens Team.' }), wave(360, [{ key: 'hammers', n: 2 }, { key: 'breachers', n: 1 }], { owner: 1, text: 'Gun teams and Breachers.' }), wave(430, [{ key: 'halo', n: 1 }, { key: 'wardens', n: 2 }], { owner: 2, text: 'A Halo column.' })],
      stages: [
        stage([obj('hold', 'hold', 'Hold 3 points for 8 minutes', { n: 3, seconds: 480 }), obj('loss', 'loseMax', 'Lose no more than 4 squads', { n: 4, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Keep the Apex central so both fronts are inside its aura.' }],
    },
    {
      key: 'blue-18', title: 'Scorched Vein', theme: 'ashfall', size: 80, seed: 'shear-18',
      story: ['Foundry Drill Rigs and Collective Siphons share the lava fields now, each guarded by the other\'s turrets.', 'The Apex sends Kites and Wedges with one instruction: leave nothing that pumps ore.'],
      briefing: 'Deep raid: destroy the extractors of both enemies without losing more than two squads.',
      epilogue: ['The lava fields are dark. Two economies starve at once.', 'Only the Foundry heartland stands between the Swarm and the Prime Vein.'],
      player: { faction: F, ore: 700, flux: 300, structures: [{ key: 'nest', at: [-4, 3] }, { key: 'spire', at: [4, -3] }], squads: [{ key: 'kites', at: [3, 4], n: 2 }, { key: 'wedges', at: [5, 2], n: 2 }] },
      enemies: [war('red', 'passive', { incomeMult: 0.9, structures: [{ key: 'drill', at: 'ore:6' }, { key: 'drill', at: 'ore:4' }, { key: 'bunker', at: 'ore:4' }], squads: [{ key: 'bolts', at: 'ore:6' }] }), war('green', 'passive', { incomeMult: 0.9, structures: [{ key: 'siphon', at: 'ore:7' }, { key: 'siphon', at: 'ore:5' }, { key: 'bastion', at: 'ore:5' }], squads: [{ key: 'lenses', at: 'ore:7' }] })],
      stages: [
        stage([obj('rigs', 'destroy', 'Destroy 2 Drill Rigs', { key: 'drill', n: 2 }), obj('siphons', 'destroy', 'Destroy 2 Siphons', { key: 'siphon', n: 2 }), obj('loss', 'loseMax', 'Lose no more than 2 squads', { n: 2 })]),
      ],
      hints: [{ at: 'start', text: 'Both enemies rebuild. Hit fast, leave, and come back for what they rebuild.' }],
    },
    {
      key: 'blue-19', title: 'The Anvil', theme: 'crystal', size: 80, seed: 'shear-19',
      story: ['The Foundry has rebuilt in the canyons with Collective Bastions at its gates. It has learned everything.', 'So has the Apex.'],
      briefing: 'Full war against a hardened Foundry with Collective support: destroy the Foundry.',
      epilogue: ['The Foundry falls for the second and last time. The Collective garrison surrenders the gates.', 'Beyond the canyons the Prime Vein hums, and every faction that is left is marching toward it.'],
      player: { faction: F, ore: 700, flux: 280 },
      enemies: [fortified('red', 'hard', { incomeMult: 1.15, structures: [{ key: 'armory', at: [-5, -3] }, { key: 'post', at: 'point:5' }] }), garrison('green', { structures: [{ key: 'bastion', at: 'point:4' }, { key: 'beacon', at: 'point:4' }], squads: [{ key: 'wardens', at: 'point:4' }, { key: 'halo', at: 'point:4' }], points: [4] })],
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('obelisk', 'train', 'Field an Obelisk', { key: 'obelisk', n: 1 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Foundry'), obj('loss', 'loseMax', 'Lose no more than 10 squads', { n: 10, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'The hard Foundry attacks early and often. Thorns and Needles at home before you push.' }],
    },
    // ---------------- FINALE
    {
      key: 'blue-20', title: 'Prime Vein', theme: 'crystal', size: 80, seed: 'shear-20',
      story: ['The Prime Vein lies open under the dunes, and around it, in three corners of the world, three peoples have built everything they have left.', 'The Foundry and the Collective will fight each other as readily as the Swarm. The Apex does not mind. The Swarm has always been the last thing standing, because it is the only one that can afford to be.'],
      briefing: 'All-out war: two living enemies, both hard, on the largest battleground. Destroy both the Foundry and the Core.',
      epilogue: ['The Foundry falls. The Core falls. The Prime Vein lies open and the Swarm pours over it in a tide of triangles.', 'The Lattice will be reforged, in the shape that divides. Campaign complete.'],
      player: { faction: F, ore: 800, flux: 320 },
      enemies: [fortified('red', 'hard', { incomeMult: 1.2, structures: [{ key: 'armory', at: [-5, -3] }] }), fortified('green', 'hard', { incomeMult: 1.2, points: [], structures: [{ key: 'sanctum', at: [-5, -3] }] })],
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('hero', 'hero', 'Field the Apex')]),
        stage([obj('hqs', 'destroyHq', 'Destroy the Foundry and the Core', { all: true }), obj('loss', 'loseMax', 'Lose no more than 15 squads', { n: 15, optional: true })], 'They will fight each other. Let them, then finish whoever wins.'),
      ],
      hints: [{ at: 'start', text: 'Three-way war: the two enemies attack each other too. Hold your corner, harvest, and strike the weaker one first.' }],
    },
  ],
};
