// Crossover events: battles that appear in more than one campaign. Each campaign reaches them at its own
// chapter number and fights its own side of them; the sides listed here are the factions that were there.
// A faction that was not there still hears of it (see the `echo` text, which the arcs weave into their own
// chapters). The three campaigns are separate stories; these are the places where they touch.
const S = (style, params, story, briefing, epilogue) => ({ style, params, story, briefing, epilogue });

export const CROSSOVERS = {
  greywater: {
    title: 'Greywater Ford', theme: 'verdant', size: 64,
    sides: {
      blue: S('assault', { rival: 'red', ranks: [2, 3] }, ['The Foundry has dug in on the far bank of the Greywater with a Watch Post at each ford. The Swarm has never crossed water it could not simply cover.', 'The Apex sends everything at the fords at once. Rivers are a Foundry idea.'], 'Assault the Foundry positions at the two fords and hold the far bank.', ['The fords fall in a single tide. Foundry rifles fire at the river long after the Swarm is past.', 'Behind the Foundry line something else burned tonight, and it was not the Swarm that lit it.']),
      red: S('chokepoint', { rival: 'blue' }, ['The Greywater is the only line between the Swarm and the Foundry\'s drill fields, and the fords are the only way across it.', 'The Foreman gives the order the Foundry was built for: nothing crosses.'], 'Chokepoint defence: fortify the near ford with Bunkers and gun teams and hold it against the swarm tide.', ['The ford holds. The far bank is carpeted with Swarm shards.', 'Behind the line, the Iron Works burned in the night. The Foreman writes it in the ledger as the Swarm\'s doing. He is wrong.']),
      green: S('commando', { rival: 'red', target: 'prod' }, ['While the Swarm and the Foundry bleed each other at the Greywater, the Oracle sends a single cell across the river in the dark.', 'The Foundry\'s Works on the near bank is making the tanks that will one day roll on the Core. It should not finish them.'], 'Commando: infiltrate the Foundry rear with the Oracle and two squads, destroy the Iron Works, and escape.', ['The Works burns behind the Foundry line, and the Foundry blames the Swarm.', 'The Oracle notes how easily the two of them believe the worst of each other. It will be useful.']),
    },
  },
  drillfields: {
    title: 'The Drill Fields', theme: 'ashfall', size: 64,
    sides: {
      blue: S('resourceRace', { rival: 'red', quota: 2200 }, ['The Ashfall drill fields hold more ore than the whole basin. The Foundry has a Works running and is claiming veins as fast as it can build rigs.', 'The Hive does not intend to fight the Foundry\'s army. It intends to have more ore than the Foundry ever will.'], 'Resource race: own four veins, hold the points and stockpile ore before the Foundry does.', ['The Hive is fat with ore and dividing faster than ever.', 'Rigs on the far edge of the field went dark during the race. Neither the Swarm nor the Foundry touched them.']),
      red: S('resourceRace', { rival: 'blue', quota: 2200 }, ['The Ashfall drill fields are the Foundry\'s future: enough ore to plate an army. The Swarm has found them too.', 'The Foreman\'s answer is rigs, and more rigs, and Bunkers between them.'], 'Resource race: own four veins, hold the points and stockpile ore before the Swarm does.', ['The stockpile is full and the Works has never run so hot.', 'Three rigs on the far edge went dark during the race, and no Swarm came near them. The ledger has a new column: unexplained.']),
      green: S('raid', { rival: 'red', n: 3 }, ['Both armies are busy with the drill fields. Neither is watching the rigs on its own flanks.', 'The Oracle prefers economies that fail quietly.'], 'Deep raid: burn three Foundry Drill Rigs on the edge of the fields and lose no more than two squads.', ['Three rigs go dark and the Foundry never learns whose beams did it.', 'The Oracle has now seen both of them fight. It begins the Long Count.']),
    },
  },
  glasslake: {
    title: 'The Glass Lake', theme: 'frost', size: 64,
    sides: {
      blue: S('raid', { rival: 'green', n: 3 }, ['The Foundry and the Collective have met on the frozen lake and neither is winning. The Collective\'s Siphons on the shore feed the whole front.', 'The Apex likes fronts that are fed from one place.'], 'Deep raid: burn three Collective Siphons on the lakeshore and lose no more than two squads.', ['The Siphons burn and the Collective line starts to starve.', 'The Swarm has met shields now. It will need a different kind of blade.']),
      red: S('assault', { rival: 'green', ranks: [2, 3] }, ['Collective Wardens on the ice behind shields that shrug off rifle fire. The Bolts empty their magazines and the Wardens do not notice.', 'Shields do not care about rifles. They care about blast.'], 'Assault: burn through Collective shields with blast and focus fire and take the lakeshore points.', ['Four Wardens are glass on the lake. The Collective withdraws to compute.', 'Its Siphons on the far shore burned while it did. The Foundry did not do that either.']),
      green: S('protectVip', { rival: 'red', ranks: [1, 2] }, ['The Foundry has crossed the ice with tanks, and it is hunting the Oracle specifically. Every Foundry squad has orders to shoot the Oracle.', 'The Oracle finds this reasonable. It would hunt itself too.'], 'Protect the VIP: keep the Oracle alive while capturing the lakeshore points and destroying the hunting parties.', ['The hunters die on the ice, and the Oracle walks off it unscratched.', 'The Siphons on the far shore are burning. Kites. The Swarm has found the Glass Front.']),
    },
  },
  halo: {
    title: 'Halo Column', theme: 'crystal', size: 64,
    sides: {
      blue: S('interdiction', { rival: 'green' }, ['A Collective column crosses the dunes under hovering rings, fed by convoys from the far veins. Nothing the Swarm throws at the column sticks.', 'Kill the convoys, the Apex decides, and the column is just Wardens.'], 'Supply interdiction: ambush the Collective convoys and burn the Siphons, then break the column\'s base.', ['The convoys stop coming and the rings go dim one by one.', 'A Foundry tank column crossed the same dunes tonight, going the other way. The Apex lets it pass. Let them spend each other.']),
      red: S('escort', { rival: 'green' }, ['The Foundry\'s answer to Halos is a Crusher column of its own, crossing the dunes to hit the Collective forward base. The dunes are full of Lenses.', 'The tank is slow. The Foreman likes slow.'], 'Escort duty: bring the Crusher Tank across the dunes through Lens ambushes to the far point.', ['The tank arrives with beam scars from nose to tail and the forward base falls to it.', 'The Collective\'s own convoys never reached its column. Something in the dunes ate them.']),
      green: S('escort', { rival: 'red' }, ['The Halo column must cross the dunes to relieve the forward base, and the Foundry has Hammer Teams on every ridge between.', 'The Halo is the only thing keeping the column alive. It must arrive.'], 'Escort duty: bring the Halo across the dunes through Foundry ambushes to the far point.', ['The Halo arrives and the forward base\'s shields come back all at once.', 'The supply convoys behind it did not. The Oracle adds the Swarm to the Long Count.']),
    },
  },
  bleed: {
    title: 'The Bleed', theme: 'crystal', size: 64,
    sides: {
      blue: S('migrate', { rival: 'red', doomAt: 300 }, ['The glow under the world has a name now: the Bleed, raw Prime Vein rising through the fracture and eating everything it touches. It is rising under the Hive.', 'The Foundry says the Burrows woke it. The Apex does not argue. It moves.'], 'Migrating base: your base will be consumed in five minutes. Rebuild in the middle of the map and survive.', ['The old Hive is crystal and silence. The new one hums in the middle of the dunes.', 'Every people in the Lattice is moving tonight. The middle of the world is about to get crowded.']),
      red: S('migrate', { rival: 'green', doomAt: 300 }, ['The Bleed rises under the Foundry: raw Prime Vein through the fracture, eating iron as easily as glass. The Foreman has five minutes.', 'The Collective says the drills woke it. The Foreman has no time to argue.'], 'Migrating base: your base will be consumed in five minutes. Rebuild in the middle of the map and survive.', ['The old Foundry is crystal and silence. The new one is a Works and two Bunkers on a point in the middle of nowhere.', 'Every people in the Lattice is moving tonight. The middle of the world is about to get crowded.']),
      green: S('migrate', { rival: 'blue', doomAt: 300 }, ['The Bleed rises under the Core. The Oracle computed this a week ago and did not tell anyone, because there was nothing to be done except leave.', 'The Swarm says the Sanctum\'s harmonics woke it. The Oracle knows better, and says nothing.'], 'Migrating base: your base will be consumed in five minutes. Rebuild in the middle of the map and survive.', ['The old Core is crystal and silence. The new one is an Array on a point with Wardens around it.', 'Every people in the Lattice is moving tonight. The middle of the world is about to get crowded.']),
    },
  },
  scavenge: {
    title: 'Scavenge', theme: 'crystal', size: 64,
    sides: {
      blue: S('scavenge', { rival: 'red' }, ['The dunes are littered with the war: stranded swarms folded flat against the crystal, a half-buried Nest, a Burrow nobody claimed. The Foundry is picking through the same wreckage.', 'The Apex was made for this. Bloom from what is left.'], 'Scavenge and build: rescue stranded squads, capture abandoned structures, and rebuild a base from nothing.', ['A Nest, a Burrow, three rescued swarms, and a Hive that is not quite a Hive yet. It is enough.', 'Somewhere in the same dunes the Foreman is doing the same, and the Oracle is doing it faster.']),
      red: S('scavenge', { rival: 'green' }, ['The dunes are littered with the war: Bolt Squads holding positions nobody remembers ordering, a Works with no Foundry, a Drill Rig still pumping. The Collective is picking through the same wreckage.', 'Doctrine says rebuild. It does not say with what.'], 'Scavenge and build: rescue stranded squads, capture abandoned structures, and rebuild a base from nothing.', ['A Works, a Rig, three rescued squads, and a Foreman. It is enough.', 'Somewhere in the same dunes the Apex is doing the same, and the Oracle is doing it faster.']),
      green: S('scavenge', { rival: 'blue' }, ['The dunes are littered with the war: Warden Cells sitting in their shields waiting, an Array with no Core, a Siphon still drinking. The Swarm is picking through the same wreckage.', 'The Oracle computed where every piece fell.'], 'Scavenge and build: rescue stranded squads, capture abandoned structures, and rebuild a base from nothing.', ['An Array, a Siphon, three rescued cells, and the Oracle. It is enough.', 'Somewhere in the same dunes the Apex and the Foreman are doing the same. The Oracle knows where.']),
    },
  },
  glasspact: {
    title: 'The Glass Pact', theme: 'frost', size: 64,
    sides: {
      blue: S('alliedAssault', { rival: 'red', ally: 'green' }, ['The Oracle sends an emissary: a truce on the ice, and a joint assault on the Foundry heartland. The Apex has never had an ally. It is curious.', 'The Collective attacks on its own schedule. The Swarm will have to learn to wait for it.'], 'Allied assault: fight beside the Collective against the Foundry heartland and keep your ally alive.', ['The Foundry heartland burns with Collective and Swarm in the same streets.', 'The Oracle says nothing about what comes next. The Apex notices.']),
      red: S('crossfire', { r1: 'blue', r2: 'green' }, ['The Swarm and the Collective have made a pact on the ice, and the Foundry heartland is the first thing they agree on.', 'Two fronts, two enemies, one line. Doctrine.'], 'Two-front defence: hold three points for eight minutes against alternating Swarm and Collective waves.', ['The heartland holds and the pact\'s armies withdraw, still allies, for now.', 'The Foreman receives an emissary of his own. From the Collective, which was shooting at him an hour ago.']),
      green: S('alliedAssault', { rival: 'red', ally: 'blue' }, ['The Oracle proposes a truce on the ice and a joint assault on the Foundry heartland. The Swarm agrees faster than the Oracle computed it would.', 'Swarms attack on their own schedule. The Collective will have to keep up.'], 'Allied assault: fight beside the Swarm against the Foundry heartland and keep your ally alive.', ['The Foundry heartland burns with Collective and Swarm in the same streets.', 'The Oracle has already computed how the pact ends. It does not tell the Apex. It sends a second emissary, to the Foreman.']),
    },
  },
  ironaccord: {
    title: 'The Iron Accord', theme: 'ashfall', size: 64,
    sides: {
      blue: S('crossfire', { r1: 'red', r2: 'green' }, ['The Foundry and the Collective have signed an accord over the ash, and the Swarm\'s new Hive is the first thing they agree on.', 'Two fronts. The Apex divides.'], 'Two-front defence: hold three points for eight minutes against alternating Foundry and Collective waves.', ['The Hive holds and the accord\'s armies withdraw, still allies, for now.', 'An emissary arrives from the Foundry. The Apex is starting to find diplomacy funny.']),
      red: S('alliedAssault', { rival: 'blue', ally: 'green' }, ['The Foreman signs an accord with the Oracle over the ash: a joint assault on the Swarm\'s new Hive. The Foundry has never trusted the Collective. It trusts doctrine, and doctrine says use what you have.', 'The Collective attacks on its own schedule. The Foundry will match it.'], 'Allied assault: fight beside the Collective against the Swarm\'s Hive and keep your ally alive.', ['The Hive burns with Foundry and Collective in the same craters.', 'The Oracle says nothing about what comes next. The Foreman notices, and sends his own emissary. To the Swarm.']),
      green: S('alliedAssault', { rival: 'blue', ally: 'red' }, ['The Oracle signs an accord with the Foreman over the ash: a joint assault on the Swarm\'s Hive. The Foundry attacks on a schedule the Oracle can read to the second.', 'That is the only kind of ally the Collective likes.'], 'Allied assault: fight beside the Foundry against the Swarm\'s Hive and keep your ally alive.', ['The Hive burns with Foundry and Collective in the same craters.', 'The Oracle has already computed how the accord ends. It has also computed that the Foreman is sending an emissary to the Apex.']),
    },
  },
  shearpact: {
    title: 'The Shear Pact', theme: 'crystal', size: 64,
    sides: {
      blue: S('alliedAssault', { rival: 'green', ally: 'red' }, ['The Foreman\'s emissary offers the Swarm a pact against the Collective: the Foundry\'s guns and the Swarm\'s numbers against the Core on the dunes.', 'The Apex agrees. It has decided to find out what betrayal feels like from the other side.'], 'Allied assault: fight beside the Foundry against the Collective\'s Core on the dunes and keep your ally alive.', ['The Core on the dunes cracks with Foundry iron and Swarm pouring through the shield.', 'The Foreman says nothing about what comes next. The Apex has learned to notice.']),
      red: S('alliedAssault', { rival: 'green', ally: 'blue' }, ['The Foreman offers the Swarm a pact against the Collective. The Apex agrees before the emissary finishes. The Foundry does not trust that either.', 'Swarms attack on their own schedule. The Foundry will keep up.'], 'Allied assault: fight beside the Swarm against the Collective\'s Core on the dunes and keep your ally alive.', ['The Core on the dunes cracks with Foundry iron and Swarm pouring through the shield.', 'The Foreman has read enough doctrine to know how pacts end. He has already chosen the minute.']),
      green: S('crossfire', { r1: 'blue', r2: 'red' }, ['The Swarm and the Foundry have made their own pact, and the Core on the dunes is the first thing they agree on.', 'The Oracle computed this. It did not enjoy it.'], 'Two-front defence: hold three points for eight minutes against alternating Swarm and Foundry waves.', ['The Core holds and the pact\'s armies withdraw, still allies, for now.', 'Every pact in the Lattice has now been made. The Oracle waits for the first one to break, and has already decided it will not be the one waiting.']),
    },
  },
  betrayal: {
    title: 'Betrayal', theme: 'urban', size: 64,
    sides: {
      blue: S('betrayal', { rival: 'green', ally: 'red', at: 360 }, ['The Foundry and the Swarm march on the Collective\'s last city together. Six minutes into the assault, the Foundry\'s guns turn around.', 'The Apex is not surprised. It is, for the first time, angry.'], 'Betrayal: fight beside the Foundry until it turns on you, then destroy both the Core and the Foundry.', ['Both the Core and the Foundry burn in the city, and the Swarm stands alone in the ash.', 'Alone is how the Swarm has always been strongest. The Bloom does not need allies. It needs the Vein.']),
      red: S('betrayal', { rival: 'blue', ally: 'green', at: 360 }, ['The Foundry and the Collective march on the Hive in the ruins together. Six minutes in, the Collective\'s beams turn around.', 'The Foreman is not surprised. Doctrine has a chapter on this, and he wrote the minute into it himself.'], 'Betrayal: fight beside the Collective until it turns on you, then destroy both the Hive and the Core.', ['Both the Hive and the Core burn in the ruins, and the Foundry stands alone.', 'Alone is how doctrine was written. The Forge was never going to be raised by committee.']),
      green: S('betrayal', { rival: 'red', ally: 'blue', at: 360 }, ['The Collective and the Swarm march on the Foundry in the ruins together. Six minutes in, the Swarm turns.', 'The Oracle computed the minute. It did not compute how it would feel.'], 'Betrayal: fight beside the Swarm until it turns on you, then destroy both the Foundry and the Hive.', ['Both the Foundry and the Hive burn in the ruins, and the Collective stands alone.', 'The Oracle has always preferred it. The Answer was never going to be spoken by three voices.']),
    },
  },
  bleedreturns: {
    title: 'The Bleed Returns', theme: 'ashfall', size: 80,
    sides: {
      blue: S('migrate', { rival: 'red', doomAt: 360 }, ['The Bleed rises again, this time under everyone at once. The Hive on the Outer Ring has six minutes.', 'The Swarm has done this before. It does it faster now, and it does not stop to blame anyone.'], 'Migrating base: the Outer Ring base will be consumed in six minutes. Rebuild in the middle and survive the Foundry.', ['The old Hive is crystal. The new one stands at the centre of the world.', 'So does everyone else\'s.']),
      red: S('migrate', { rival: 'green', doomAt: 360 }, ['The Bleed rises again, under everyone at once. The Foundry on the Outer Ring has six minutes.', 'Doctrine has a chapter on this now. The Foreman wrote it.'], 'Migrating base: the Outer Ring base will be consumed in six minutes. Rebuild in the middle and survive the Collective.', ['The old Foundry is crystal. The new one stands at the centre of the world.', 'So does everyone else\'s.']),
      green: S('migrate', { rival: 'blue', doomAt: 360 }, ['The Bleed rises again, under everyone at once. The Core on the Outer Ring has six minutes.', 'The Oracle computed this a week ago. This time it told everyone, and nobody listened.'], 'Migrating base: the Outer Ring base will be consumed in six minutes. Rebuild in the middle and survive the Swarm.', ['The old Core is crystal. The new one stands at the centre of the world.', 'So does everyone else\'s.']),
    },
  },
  threecorners: {
    title: 'Three Corners', theme: 'frost', size: 64,
    sides: {
      blue: S('threeWay', { r1: 'red', r2: 'green' }, ['Three armies in three corners of the ice, and the Prime Vein between them. Nobody is allied with anybody.', 'The Apex has waited its whole existence for a fight with no rules.'], 'Three-way war: destroy both the Foundry and the Core on the ice.', ['Two headquarters burn on the ice and the Swarm holds the lake.', 'Both of them will rebuild. Both of them will be at the Vein. The Bloom will have to go through them.']),
      red: S('threeWay', { r1: 'blue', r2: 'green' }, ['Three armies in three corners of the ice, and the Prime Vein between them. Nobody is allied with anybody.', 'Doctrine has always assumed this.'], 'Three-way war: destroy both the Hive and the Core on the ice.', ['Two headquarters burn on the ice and the Foundry holds the lake.', 'Both of them will rebuild. Both of them will be at the Vein. The Forge will have to be raised over them.']),
      green: S('threeWay', { r1: 'blue', r2: 'red' }, ['Three armies in three corners of the ice, and the Prime Vein between them. Nobody is allied with anybody.', 'The Oracle computed this ending before the war began.'], 'Three-way war: destroy both the Hive and the Foundry on the ice.', ['Two headquarters burn on the ice and the Collective holds the lake.', 'Both of them will rebuild. Both of them will be at the Vein. The Answer will have to be spoken over them.']),
    },
  },
};
