// Protocol, chapters 6-40: the Aegis Collective's own story. Its goal is the Answer.
import { C, X } from './arc.js';

const RED_GATE = [{ faction: 'red', hq: false, ai: null, structures: [{ key: 'bunker', at: 'point:4' }, { key: 'post', at: 'point:4' }], squads: [{ key: 'bolts', at: 'point:4' }, { key: 'hammers', at: 'point:4', order: 'hold' }], points: [4] }];

export const GREEN_ARC = {
  goal: 'The Answer',
  backstory: 'The Oracle has read the fracture to its end. The Lattice is still breaking, slowly, and the Bleed is what breaking looks like from below. The Swarm\'s Burrows and the Foundry\'s drills only hurry it. The Answer is stillness: carry the Collective\'s harmonics to the Prime Vein, hold them there until the seam sets, and the world stops moving, forever. No division, no forging, no dreams. Only endurance. The Swarm calls it death. The Foundry calls it surrender. The Oracle calls it the Answer, and it has computed that both of them will have to be quiet before it can be spoken.',
  outcome: 'The Oracle settles over the seam of the Prime Vein and the harmonics take hold. The Lattice is reforged in the shape that endures: still, whole, and silent, with the Collective keeping watch until the end of time.',
  acts: [
    { title: 'Act I · Awakening', from: 0 }, { title: 'Act II · The Long Count', from: 5 }, { title: 'Act III · The Glass Front', from: 10 },
    { title: 'Act IV · The Bleed', from: 15 }, { title: 'Act V · Recompute', from: 20 }, { title: 'Act VI · Emissaries', from: 25 },
    { title: 'Act VII · Alone', from: 30 }, { title: 'Act VIII · The Answer', from: 35 },
  ],
  chapters: [
    // ---- Act II · The Long Count (6-10): the Oracle watches the Swarm and the Foundry fight, and takes notes.
    C('The Frost Field', 'frost', 64, 2, 'raid', { rival: 'red', n: 3 },
      ['The Foundry has a drill field in the frost on the Collective\'s border, and the rigs are going down further every day. The Oracle has computed exactly how far they can go before the ground answers.', 'It sends Lenses to make sure they never find out.'],
      'Deep raid: burn three Foundry Drill Rigs on the frost field and lose no more than two squads.',
      ['The rigs burn and the Foundry never learns whose beams did it.', 'To the south the Swarm and the Foundry are about to meet at a river. The Oracle would like to be behind one of them when they do.']),
    X('greywater', 2),
    C('The Beacon Line', 'frost', 64, 3, 'holdTheLine', { rival: 'blue', minutes: 6, points: 3, waves: 5 },
      ['The Collective\'s Beacons on the ice have watched the whole Basin war and never fired a shot. The Swarm has decided that watching is an act of war.', 'The Oracle agrees, in principle. It does not move Beacons. It moves everything else around them.'],
      'Hold the line: keep three points on the Beacon line against swarm waves for six minutes.',
      ['The waves stop. The line belongs to whoever is left, and the Collective is left.', 'The Oracle has now seen the Swarm fight up close. It begins the Long Count: the number of minutes until the Vein must be stilled.']),
    X('drillfields', 3),
    C('Sanctum Rising', 'crystal', 64, 3, 'protectStructure', { rival: 'blue' },
      ['A Sanctum is growing at the Collective\'s forward point in the dunes, the first instrument of the Answer: it harmonises every shield within its reach, and one day it will harmonise a seam. It has no shield of its own yet.', 'The Swarm has noticed it, and sent Kites. The Oracle cannot let it fall. Everything the Collective will become is inside it.'],
      'Protect the unfinished Sanctum from Swarm raids for six minutes, then destroy the raiders\' Claim Spikes.',
      ['The Sanctum finishes its shield with Kites burning around it, and for the first time the ground under it goes quiet.', 'The Foundry has crossed the ice with tanks, and it is hunting the Oracle specifically.']),
    // ---- Act III · The Glass Front (11-15): the Foundry comes across the ice, and the Swarm raids both.
    X('glasslake', 3),
    C('Beacon Hill', 'urban', 64, 4, 'chokepoint', { rival: 'red' },
      ['Beacon Hill is the one high place in the Ruined City, and the Foundry wants it. The only road up is a single boulevard.', 'One boulevard, two Bastions, and the Oracle watching the whole approach.'],
      'Chokepoint defence: hold the boulevard up Beacon Hill with Bastions and Lenses.',
      ['The boulevard is iron scrap from end to end. The hill holds.', 'The Halo column is ready to move. It will need an escort, and the Swarm has found the Glass Front.']),
    X('halo', 4),
    C('Nova Rain', 'ashfall', 64, 4, 'multiFront', { rival: 'red' },
      ['The Novas fire from two bases at once, and the Foundry answers both. The Collective has to hold both or lose both.', 'The Oracle can watch two things at once. It has never had to fight two things at once.'],
      'Multi-front: hold your two bases against Foundry pushes, then destroy the Foundry forward base.',
      ['Both bases hold. The Foundry falls back from the plain.', 'Under the craters the Novas left, something is glowing. The Oracle has a word for it. It has had the word for years.']),
    C('The Sanctum', 'frost', 64, 4, 'protectStructure', { rival: 'red' },
      ['The Sanctum is the Collective\'s heart on the front and the only thing in the Lattice that can still a seam. The Foundry is coming for it with everything, and the Swarm is coming for it from behind.', 'The Oracle stands beside it and does not move.'],
      'Protect the Sanctum from Foundry raids for six minutes, then destroy the raiders\' Watch Posts.',
      ['The Sanctum stands, scorched. The Foundry falls back across the ice.', 'The ice is melting from below. The Bleed has reached the glass lakes, and the Long Count is shorter than the Oracle computed.']),
    // ---- Act IV · The Bleed (15-20): the Oracle computed it a week ago. There was nothing to do but leave.
    X('bleed', 4),
    C('The Walled City', 'urban', 64, 4, 'tugOfWar', { rival: 'red' },
      ['The Foundry has walled the Ruined City street by street. The Collective takes it the same way: street by street.', 'Each block taken is a Beacon planted, and a Beacon is a place the Oracle can see from.'],
      'Tug-of-war: push through the walled city block by block; each block taken brings reinforcements.',
      ['The last block falls and the Foundry retreats into the Ashfall.', 'The Ashfall is where the Bleed began. There is nothing there but craters, the Foundry, and the Swarm holding the only crossing.']),
    C('Ashfall Crossing', 'ashfall', 64, 5, 'countdown', { rival: 'blue', minutes: 12, waves: 8 },
      ['The Collective holds the Ashfall crossing with a half-built base and the Swarm on three sides. Relief is twelve minutes away.', 'The Oracle has computed exactly how many shields twelve minutes cost.'],
      'Survive the countdown: hold the Ashfall crossing for twelve minutes until relief arrives, then counter-attack.',
      ['Relief arrives with a Nova and the swarms scatter across the craters.', 'The Swarm is hitting two Collective bases on the ice at once, because it can.']),
    C('Two Cores', 'frost', 64, 5, 'multiFront', { rival: 'blue' },
      ['Two Collective bases on the ice, and the Swarm hitting both because it can. The Oracle can see both. It cannot be at both.', 'Halos can.'],
      'Multi-front: hold both bases against swarm pushes, then destroy the Swarm\'s forward base.',
      ['Both bases hold and the Swarm\'s Nest on the ice burns.', 'The winter is ending. The Swarm has bloomed in the ruins all through it, and the Oracle has computed the answer.']),
    C('The Winter Push', 'urban', 80, 5, 'war', { rival: 'blue' },
      ['The Swarm has bloomed in the ruins through the winter and the Hive squats on the last dry ground. The Oracle has computed the answer.', 'Deliver it.'],
      'Full war against a living Swarm: destroy the Hive in the ruins.',
      ['The Hive collapses into itself, a pyramid of dark glass.', 'Then the Bleed comes for the ruins too, and the Core with them. The Oracle did compute that. It went anyway.']),
    // ---- Act V · Recompute (21-25): the Core is crystal. The Oracle knows exactly where every piece fell.
    X('scavenge', 5),
    C('Ashes', 'ashfall', 64, 5, 'commando', { rival: 'red', target: 'prod' },
      ['The scavenged Core is a shell, and the Foundry has a Works in the ash, making tanks to come and finish it.', 'The Oracle has computed that it should not. It goes itself, with a Warden Cell and a Lens Team.'],
      'Commando: with no base, infiltrate the Foundry facility in the ash with the Oracle, destroy the Works, and escape.',
      ['The Works burns and the Oracle walks out of the ash with both squads.', 'The last Nova in the Collective is on the wrong side of the ice. The Swarm knows.']),
    C('The Nova Road', 'frost', 64, 5, 'escort', { rival: 'blue' },
      ['The scavenged Nova is the Collective\'s only star left in the world, and it is on the wrong side of the ice. The Swarm knows.', 'It rolls. The Halo goes with it.'],
      'Escort duty: bring the Nova Sphere across the ice through swarm ambushes to the far outpost.',
      ['The Nova arrives with Wedge blades still stuck in its shield.', 'The Swarm\'s new Hive is a fortress. It is fed by a road, and roads can be cut.']),
    C('Starve the Hive', 'urban', 64, 5, 'interdiction', { rival: 'blue' },
      ['The Hive in the ruins cannot be stormed: Thorns in every window, the Apex inside. It is fed by convoys of Kites from the far Burrows.', 'The Oracle computes that hunger is faster than beams.'],
      'Supply interdiction: ambush the Swarm convoys and burn the Burrows, then break the starving Hive.',
      ['The convoys stop and the Hive\'s hum thins to nothing.', 'The frozen river is the last line between the Collective and the Swarm heartland.']),
    C('The Crossing', 'frost', 64, 6, 'tugOfWar', { rival: 'blue' },
      ['The frozen river has five outposts along it, Swarm on every one. The Collective takes them one Beacon at a time.', 'Each Beacon is a place the Oracle can see from. Soon it will see the far bank.'],
      'Tug-of-war: push across the frozen river outpost by outpost; each one taken brings reinforcements.',
      ['The far bank is Collective. The Swarm\'s Nest on it is burning.', 'The Oracle has computed the next five moves, and the first of them is an emissary. To the Apex.']),
    // ---- Act VI · Emissaries (26-30): the Oracle makes every pact in the Lattice, and computes how each one ends.
    X('glasspact', 6),
    X('ironaccord', 6),
    X('shearpact', 6),
    X('betrayal', 6),
    C('The Reckoning', 'crystal', 80, 6, 'war', { rival: 'blue' },
      ['The Swarm\'s betrayal has a price. The Collective goes to collect it at the Hive\'s dune fortress with everything it has.', 'There will be no more pacts. The Answer is spoken by one voice.'],
      'Full war: destroy the Hive at its dune fortress.',
      ['The Hive falls. The Swarm scatters across the dunes.', 'The Foundry and the Swarm have both learned the same lesson about the Collective. They will learn it together.']),
    // ---- Act VII · Alone (31-35): the other two peoples unite against the Answer.
    C('Two Banners', 'verdant', 64, 7, 'twoBanners', { r1: 'blue', r2: 'red' },
      ['Swarm Thorns and Foundry Bunkers on the same ridge. The old enemies have decided the Collective is the newer problem.', 'The Oracle computed this outcome some time ago.'],
      'Mixed garrison: clear a ridge held by both Swarm and Foundry forces and take every point on it.',
      ['The ridge falls. The two garrisons never learned to fight together, only to die together.', 'Both strongholds are now sending everything they have, timed to arrive at once.']),
    C('Crossfire', 'urban', 80, 7, 'crossfire', { r1: 'blue', r2: 'red', minutes: 9 },
      ['The coalition attacks from both corners of the city at once, Kites over the roofs and Mortars behind.', 'The Collective has an Array, three points and nine minutes to prove that shields, given a breath, come back.'],
      'Two-front defence: hold three points for nine minutes against alternating Swarm and Foundry waves.',
      ['The city is quiet and the streets are full of Swarm and Foundry dead.', 'Their economies are exposed. The Oracle has already mapped them.']),
    C('Scorched Vein', 'ashfall', 80, 7, 'raid', { rival: 'blue', n: 4 },
      ['Lode Burrows and Drill Rigs share the lava fields, guarded by Thorns and Bunkers.', 'The Oracle sends Lenses and a Halo with one instruction: nothing that pumps ore is to be left standing.'],
      'Deep raid: destroy four coalition extractors on the lava fields without losing more than two squads.',
      ['The lava fields are dark. Two economies starve at once.', 'Only the Swarm\'s canyon fortress stands between the Collective and the Prime Vein.']),
    C('The Anvil', 'crystal', 80, 7, 'war', { rival: 'blue', extraEnemies: RED_GATE },
      ['The Swarm has rebuilt in the canyons with Foundry Bunkers at its gates, on the one place in the Lattice where the seam comes close enough to the surface to hear. It has learned everything.', 'So has the Oracle. It has been listening to that seam for years.'],
      'Full war against a hardened Swarm with Foundry support at its gates: destroy the Hive.',
      ['The Hive falls for the last time. The Foundry garrison surrenders the gates.', 'Beyond the canyons the seam is loud enough for anyone to hear. The Long Count is nearly done.']),
    C('The Approaches', 'crystal', 64, 7, 'protectVip', { rival: 'red', ranks: [1, 2, 3] },
      ['The approaches to the Prime Vein are three points on a ridge, and the Foundry holds them. The Oracle must take them itself; the Collective will not advance without it.', 'The Foundry knows. Every Hammer Team on the ridge is set up facing the Oracle.'],
      'Protect the VIP: keep the Oracle alive while it leads the capture of the three approach points.',
      ['Three points, and the Oracle still standing on the last of them.', 'The Vein is in sight. The Oracle has seen it for years. It is louder than the computation said.']),
    // ---- Act VIII · The Answer (36-40): the end of the world, the Collective's way.
    C('The Outer Ring', 'crystal', 80, 8, 'resourceRace', { rival: 'red', quota: 3000, minutes: 15 },
      ['The Outer Ring of the Prime Vein is the richest ore in the Lattice, and the Foundry is drilling it as fast as the Collective can drink.', 'The harmonics will need every shield the Collective can raise. Whoever has more when the Bleed returns wins the war before it starts.'],
      'Resource race: own the Outer Ring veins and stockpile three thousand ore before the Foundry does.',
      ['The stockpile is full. Every shield in the Collective hums at once.', 'And the ground under it is glowing again.']),
    X('bleedreturns', 8),
    C('Last Star', 'crystal', 80, 8, 'escort', { rival: 'red' },
      ['The last Nova in the world rolls from the Array to the centre, and both other peoples want it dead before it arrives.', 'It arrives, or the Answer stays unspoken.'],
      'Escort duty: bring the last Nova Sphere to the centre through Foundry ambushes.',
      ['The Nova stands at the centre of the world with the Collective around it.', 'The other two armies are already there, in their corners, building.']),
    X('threecorners', 8),
    C('The Answer', 'crystal', 80, 8, 'finale', {
      r1: 'blue', r2: 'red',
      goal: [{ id: 'oracle', type: 'heroAt', text: 'Bring the Oracle to the seam of the Prime Vein', at: 'center', radius: 5 }, { id: 'still', type: 'hold', text: 'Stillness: hold five points for three minutes while the seam sets', n: 5, seconds: 180 }],
      goalIntro: 'Both of them are quiet. The seam is open. Bring the Oracle to it and hold the world still while it sets.',
    },
      ['The Prime Vein lies open under the dunes, and around it, in three corners of the world, three peoples have built everything they have left. The Swarm wants to be it. The Foundry wants to forge it.', 'The Collective wants it to stop. The Oracle computed this ending before the war began, and it will have to go through both of them to speak it.'],
      'The finale: destroy both the Hive and the Foundry, then bring the Oracle to the seam and hold the ground while it sets.',
      ['The Hive falls. The Foundry falls. The Oracle settles over the seam of the Prime Vein and the harmonics take hold, and for the first time since the fracture, nothing in the Lattice moves.', 'The Lattice is reforged in the shape that endures. Still, whole, and silent, with the Collective keeping watch until the end of time. Campaign complete.']),
  ],
};
