// Campaign: Protocol (Aegis Collective). Twenty chapters in four acts.
import { garrison, war, obj, stage, wave, fortified } from './common.js';

const F = 'green';
export const GREEN = {
  faction: F, title: 'Protocol', tagline: 'Endure. Observe. Answer.',
  intro: 'The Collective wakes last, as it always does, having computed the others\' first moves before making its own. Its spheres are few and each is precious, wrapped in shields that heal if given a breath. The Oracle has read the fracture. The answer is already decided; the Collective only has to survive long enough to give it.',
  acts: [{ title: 'Act I · Awakening', from: 0 }, { title: 'Act II · Iron in the Frost', from: 5 }, { title: 'Act III · The Bloom', from: 10 }, { title: 'Act IV · The Coalition', from: 15 }, { title: 'Finale', from: 19 }],
  chapters: [
    // ---------------- ACT I
    {
      key: 'green-1', title: 'Awakening', theme: 'crystal', size: 48, seed: 'protocol-1',
      story: ['The Core opens on the Crystal Dunes. Foundry sentinels stand on the near points, left behind by a war that moved on without them.', 'You have three Wardens. Each is worth ten of anything else on this sand, if you never let one die.'],
      briefing: 'Learn the basics: train Warden Cells, mine ore, capture a point, and pull back to let shields recharge.',
      epilogue: ['Not one Warden lost. The Foundry sentinels are glass on the sand.', 'The Oracle reads new shapes in the fracture: Crusher Tanks moving across Frostbite towards the Core.'],
      player: { faction: F, ore: 320, flux: 70, units: ['wardens'], buildings: ['siphon'] },
      enemy: garrison('red', { squads: [{ key: 'bolts', at: 'point:2', hp: 0.8 }, { key: 'bolts', at: 'point:1' }], points: [1, 2] }),
      stages: [
        stage([obj('train', 'train', 'Train 2 Warden Cells', { key: 'wardens', n: 2, hint: 'Tap the Core, then Warden Cell.' }), obj('siphon', 'build', 'Build a Siphon on an ore vein', { key: 'siphon', n: 1 })]),
        stage([obj('cap', 'capture', 'Capture the nearest point', { rank: 0 }), obj('regen', 'shieldRegen', 'Pull a damaged Warden Cell back until its shields refill', { hint: 'Move a squad out of the fight (or tap Retreat). Rings around each orb show shield strength.' })], 'Shields absorb damage first and recharge when a squad is left alone. Fight, pull back, recharge, return.'),
        stage([obj('kill', 'kill', 'Destroy both Bolt Squads', { n: 2 }), obj('cap2', 'capture', 'Hold 3 strategic points', { n: 3 }), obj('loss', 'loseMax', 'Lose no squads', { n: 0, optional: true })], 'Now answer.'),
      ],
      hints: [{ at: 'start', text: 'Wardens outrange Bolts. Fire, step back, fire.' }],
    },
    {
      key: 'green-2', title: 'Long Sight', theme: 'frost', size: 48, seed: 'protocol-2',
      story: ['Frostbite. Crusher Tanks on the ice, escorting drill crews to veins the Collective was saving.', 'The Core answers with the Lens Team: two spheres that focus light into a beam that can cross a frozen lake and open a tank like a tin. They see further than anything alive. They must, because they die to a stiff breeze.'],
      briefing: 'Range and vision: field Lens Teams, kill armour from beyond its reach, and take the veins back.',
      epilogue: ['The tanks burn on the ice with no idea where the beams came from.', 'The Oracle notes a new pattern: the Foundry is fortifying the drill fields with Bunkers.'],
      player: { faction: F, ore: 480, flux: 110, units: ['wardens', 'lenses'], buildings: ['siphon', 'bastion'], squads: [{ key: 'wardens', at: [3, 4] }] },
      enemy: garrison('red', { structures: [{ key: 'drill', at: 'ore:3' }, { key: 'drill', at: 'ore:4' }], squads: [{ key: 'crusher', at: 'ore:3' }, { key: 'crusher', at: 'point:3' }, { key: 'bolts', at: 'point:3' }, { key: 'bolts', at: 'point:1' }], points: [1, 3] }),
      waves: [wave(200, [{ key: 'bolts', n: 2 }], { from: 'point:3', target: 'point:0', text: 'Foundry infantry moving on your point.' })],
      stages: [
        stage([obj('lenses', 'train', 'Train 2 Lens Teams', { key: 'lenses', n: 2 }), obj('cap', 'capture', 'Capture the nearest point', { rank: 0 })]),
        stage([obj('tanks', 'kill', 'Destroy 2 Crusher Tanks', { armor: 'vehicle', n: 2 }), obj('rigs', 'destroy', 'Destroy the Drill Rigs', { key: 'drill', n: 2 })], 'Lenses outrange tanks. Wardens in front to absorb, Lenses behind to kill.'),
        stage([obj('siphon', 'build', 'Own 3 Siphons', { key: 'siphon', n: 3 }), obj('cap3', 'capture', 'Hold 3 points', { n: 3 })], 'Claim what they were stealing.'),
      ],
      hints: [{ at: 'start', text: 'Lens Teams have 8.5 range and 11 sight. Keep them at the back; they die in melee.' }],
    },
    {
      key: 'green-3', title: 'Halo', theme: 'ashfall', size: 64, seed: 'protocol-3',
      story: ['The Ashfall: a Foundry drill field bristling with Bunkers, and Watch Posts on every point.', 'The Collective cannot trade losses with the Foundry; it does not have the numbers. So it fields the Halo, a hovering disc that recharges every shield near it. An army that never runs out of shields never has to stop.'],
      briefing: 'Sustain: field a Halo, keep the army inside its aura, and take the Foundry outposts without losing squads.',
      epilogue: ['The outposts fall and the Collective\'s losses are counted on one hand.', 'The Oracle rises. It has seen where the Foundry\'s ore comes from.'],
      player: { faction: F, ore: 600, flux: 200, units: ['wardens', 'lenses', 'pulsers', 'halo'], buildings: ['siphon', 'array', 'bastion', 'beacon'], structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'wardens', at: [3, 4] }, { key: 'lenses', at: [5, 2] }] },
      enemy: garrison('red', { structures: [{ key: 'post', at: 'point:2' }, { key: 'bunker', at: 'point:2' }, { key: 'post', at: 'point:4' }, { key: 'bunker', at: 'point:4' }, { key: 'drill', at: 'ore:4' }], squads: [{ key: 'bolts', at: 'point:2' }, { key: 'hammers', at: 'point:4', order: 'hold' }, { key: 'bolts', at: 'point:4' }], points: [2, 4] }),
      stages: [
        stage([obj('halo', 'train', 'Field a Halo', { key: 'halo', n: 1 }), obj('pop', 'pop', 'Raise an army of 16 population', { n: 16 })]),
        stage([obj('posts', 'destroy', 'Destroy both Watch Posts', { key: 'post', n: 2 }), obj('bunkers', 'destroy', 'Destroy both Bunkers', { key: 'bunker', n: 2 }), obj('loss', 'loseMax', 'Lose at most 1 squad', { n: 1, optional: true })], 'Keep everything inside the Halo\'s ring. Rotate damaged squads to the back; they will be full again in seconds.'),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 })]),
      ],
      hints: [{ at: 'start', text: 'The Halo is a vehicle: anti-armour fire hurts it. Keep it behind the Wardens.' }],
    },
    {
      key: 'green-4', title: 'The Oracle', theme: 'urban', size: 64, seed: 'protocol-4',
      story: ['The Ruined City hides the Foundry\'s supply: Drill Rigs tucked into courtyards, invisible from the streets. The Foundry is alive here, and it is watching the roads.', 'The Oracle takes the field. It sees through the fog further than anything in the Lattice. Find the rigs. Starve the city.'],
      briefing: 'Vision and hero: train the Oracle, attach it, find and destroy the hidden Drill Rigs, and fortify a point with a Beacon.',
      epilogue: ['Three rigs burn in three courtyards. The city\'s bunkers go quiet for want of ore.', 'The Foundry answers with gun teams. The Oracle has already seen them coming.'],
      player: { faction: F, ore: 650, flux: 220, structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'wardens', at: [3, 4] }, { key: 'pulsers', at: [5, 2] }] },
      enemy: war('red', 'passive', { incomeMult: 0.9, structures: [{ key: 'drill', at: 'ore:3' }, { key: 'drill', at: 'ore:5' }, { key: 'drill', at: 'ore:6' }, { key: 'bunker', at: 'point:4' }, { key: 'post', at: 'point:4' }], squads: [{ key: 'bolts', at: 'ore:3' }, { key: 'hammers', at: 'ore:5', order: 'hold' }] }),
      stages: [
        stage([obj('hero', 'hero', 'Train the Oracle'), obj('attach', 'attach', 'Attach the Oracle to a squad')]),
        stage([obj('rigs', 'destroy', 'Find and destroy 3 hidden Drill Rigs', { key: 'drill', n: 3 }), obj('beacon', 'build', 'Build a Beacon on a captured point', { key: 'beacon', n: 1 })], 'The Oracle sees 14 tiles. Walk the courtyards; the rigs will appear on the minimap once seen.'),
        stage([obj('cap', 'capture', 'Hold 4 points', { n: 4 })]),
      ],
      hints: [{ at: 'start', text: 'The Foundry here defends but does not attack. Take your time; scout before you commit.' }],
    },
    {
      key: 'green-5', title: 'Bastion Line', theme: 'frost', size: 64, seed: 'protocol-5',
      story: ['The Foundry comes back across the ice in earnest: Hammer Teams, Breachers, Bolts in waves, a tank behind them.', 'The Collective answers with the Bastion: a Lens Team that stopped moving and grew a shield the size of a house. Two of them, and a Halo, and the ice becomes a wall.'],
      briefing: 'Static defence: build Bastions, hold three points, and let the Foundry waves break on your line.',
      epilogue: ['The last Breacher dies at the foot of a Bastion it never reached.', 'The Foundry has a drill field in the frost, and the Oracle has computed exactly how to take it.'],
      player: { faction: F, ore: 700, flux: 260, structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'wardens', at: [3, 4], n: 2 }, { key: 'lenses', at: [5, 2] }, { key: 'halo', at: [2, 6] }], points: [0, 1, 2] },
      enemy: garrison('red', { points: [4, 5] }),
      waves: [wave(70, [{ key: 'bolts', n: 2 }], { text: 'Bolt Squads on the ice.' }), wave(150, [{ key: 'hammers', n: 2 }], { text: 'Gun teams: hit them before they set up.' }), wave(240, [{ key: 'breachers', n: 2 }, { key: 'bolts', n: 1 }], { text: 'Breachers: they will go for the Bastions.' }), wave(330, [{ key: 'crusher', n: 1 }, { key: 'bolts', n: 2 }], { text: 'Armour. Lenses forward.' }), wave(420, [{ key: 'bolts', n: 3 }, { key: 'hammers', n: 1 }], { text: 'Their last push.' })],
      stages: [
        stage([obj('bastion', 'build', 'Build 2 Bastions', { key: 'bastion', n: 2 })]),
        stage([obj('hold', 'hold', 'Hold 3 points for 7 minutes', { n: 3, seconds: 420 }), obj('loss', 'loseMax', 'Lose no more than 2 squads', { n: 2, optional: true })], 'Bastions at the approaches, Wardens between them, the Halo behind.'),
      ],
      hints: [{ at: 'start', text: 'A Bastion beside a Beacon holds a point on its own. Put them where the waves must pass.' }],
    },
    // ---------------- ACT II: Iron in the Frost
    {
      key: 'green-6', title: 'Drill Fields', theme: 'ashfall', size: 64, seed: 'protocol-6',
      story: ['The Ashfall drill fields, alive with Foundry industry: a Works running, Bunkers on the roads, and rigs on every vein.', 'The Oracle does not intend to fight the army the Foundry is building. It intends to own more veins than the Foundry ever will, and let the numbers argue.'],
      briefing: 'Economy race: own four Siphons and hold four points before the Foundry does, then break its Works.',
      epilogue: ['The Works falls silent for want of ore, then falls.', 'The Foundry pulls back through the frost passes. The Oracle already knows which ones.'],
      player: { faction: F, ore: 500, flux: 120 },
      enemy: war('red', 'normal', { incomeMult: 0.95, structures: [{ key: 'works', at: [4, -2] }, { key: 'drill', at: 'ore:6' }, { key: 'drill', at: 'ore:7' }, { key: 'bunker', at: [-3, 3] }], squads: [{ key: 'bolts', at: [0, 5] }] }),
      timeLimit: 900,
      stages: [
        stage([obj('siphon', 'build', 'Own 4 Siphons', { key: 'siphon', n: 4 }), obj('cap', 'capture', 'Hold 4 strategic points', { n: 4 })], 'Fifteen minutes. Expand faster than the Foundry.'),
        stage([obj('works', 'destroy', 'Destroy the Iron Works', { key: 'works', n: 1 })]),
      ],
      hints: [{ at: 'start', text: 'Contested veins in the middle are worth a fight. Take them with Wardens and Beacon the nearest point.' }],
    },
    {
      key: 'green-7', title: 'Frost Passes', theme: 'frost', size: 64, seed: 'protocol-7',
      story: ['Hammer Teams in every pass, dug in behind rubble, with Bunkers behind them. A Warden that walks into a pass does not walk out.', 'Pulse Rings do not walk into passes. They stand at the mouth and ring until nobody inside remembers why they are there.'],
      briefing: 'Morale warfare: break the gun teams holding the passes with Pulse Rings and finish them with Wardens.',
      epilogue: ['Three gun teams lie in three passes. The ice is open.', 'Beyond it, Mortar Blocks. The Foundry has decided to stop being reached.'],
      player: { faction: F, ore: 650, flux: 220, structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'wardens', at: [3, 4], n: 2 }, { key: 'pulsers', at: [5, 2] }] },
      enemy: garrison('red', { structures: [{ key: 'bunker', at: 'point:3' }, { key: 'post', at: 'point:4' }], squads: [{ key: 'hammers', at: 'point:1', order: 'hold' }, { key: 'hammers', at: 'point:3', order: 'hold' }, { key: 'hammers', at: 'point:4', order: 'hold' }, { key: 'bolts', at: 'point:3' }, { key: 'bolts', at: 'point:4' }], points: [1, 3, 4] }),
      stages: [
        stage([obj('pulsers', 'train', 'Field 2 Pulse Rings', { key: 'pulsers', n: 2 })]),
        stage([obj('broken', 'broken', 'Break 4 Foundry squads', { n: 4 }), obj('hammers', 'kill', 'Destroy 3 Hammer Teams', { key: 'hammers', n: 3 })], 'Rings at the mouth of the pass, Wardens beside them. Break, then finish.'),
        stage([obj('cap', 'capture', 'Hold 4 points', { n: 4 })]),
      ],
      hints: [{ at: 'start', text: 'Never approach a Hammer Team from the front. Rings from the side, Wardens from the other side.' }],
    },
    {
      key: 'green-8', title: 'Steel Rain', theme: 'urban', size: 64, seed: 'protocol-8',
      story: ['Mortar Blocks behind the city walls, dropping shells on anything the Beacons see. Shields do not last under a bombardment.', 'They do not have to last. They have to be somewhere else when the shell lands.'],
      briefing: 'Artillery: survive a Mortar bombardment, then run the guns down before their escort can turn.',
      epilogue: ['The last Mortar crew dies with a Warden standing over it. The walls are quiet.', 'The Foundry is building something heavier at its Works. The Oracle wants the Works.'],
      player: { faction: F, ore: 700, flux: 260, structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'wardens', at: [3, 4], n: 2 }, { key: 'pulsers', at: [5, 2] }, { key: 'halo', at: [2, 6] }] },
      enemy: garrison('red', { structures: [{ key: 'bunker', at: 'point:4' }], squads: [{ key: 'mortar', at: 'point:4', order: 'hold' }, { key: 'mortar', at: 'point:5', order: 'hold' }, { key: 'bolts', at: 'point:4' }, { key: 'hammers', at: 'point:5', order: 'hold' }], points: [4, 5] }),
      waves: [wave(90, [{ key: 'mortar', n: 1 }, { key: 'bolts', n: 1 }], { from: 'point:5', target: 'point:0', text: 'A Mortar Block is moving on your point.' }), wave(240, [{ key: 'crusher', n: 1 }, { key: 'bolts', n: 2 }], { from: 'point:4', target: 'point:2', text: 'Armour behind the shells.' })],
      stages: [
        stage([obj('mortars', 'kill', 'Destroy 3 Mortar Blocks', { key: 'mortar', n: 3, hint: 'Get inside their minimum range.' }), obj('survive', 'survive', 'Survive the bombardment (6 minutes)', { seconds: 360 })]),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 })]),
      ],
      hints: [{ at: 'start', text: 'Mortar shells land where you were. Keep squads moving, and never clump.' }],
    },
    {
      key: 'green-9', title: 'The Works', theme: 'crystal', size: 64, seed: 'protocol-9',
      story: ['An Iron Works in the canyons, turning out Crushers, with an Armoury beside it plating everything that walks out. The Foundry defends it and does not attack.', 'The Oracle wants both buildings gone before the next tank finishes.'],
      briefing: 'Assault: destroy the Iron Works and the Armoury behind their Bunker line, against a Foundry that defends but does not attack.',
      epilogue: ['The Works cracks open on a half-built tank. The Armoury burns.', 'The Foundry itself is all that remains, and the Oracle has known where it was for some time.'],
      player: { faction: F, ore: 700, flux: 260, structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'wardens', at: [3, 4], n: 2 }, { key: 'lenses', at: [5, 2] }, { key: 'halo', at: [2, 6] }] },
      enemy: war('red', 'passive', { incomeMult: 1.0, structures: [{ key: 'works', at: [4, -2] }, { key: 'armory', at: [-4, 3] }, { key: 'bunker', at: [-3, -3] }, { key: 'bunker', at: [3, 3] }, { key: 'drill', at: 'ore:6' }, { key: 'drill', at: 'ore:7' }], squads: [{ key: 'bolts', at: [0, 5], n: 2 }, { key: 'hammers', at: [-3, 2], order: 'hold' }, { key: 'crusher', at: [3, -4] }] }),
      stages: [
        stage([obj('econ', 'capture', 'Hold 3 points', { n: 3 })]),
        stage([obj('works', 'destroy', 'Destroy the Iron Works', { key: 'works', n: 1 }), obj('armory', 'destroy', 'Destroy the Armoury', { key: 'armory', n: 1 })], 'Lenses on the Bunkers from range, Wardens for the escort, the Halo behind everything.'),
      ],
      hints: [{ at: 'start', text: 'The Foundry will not attack, but it defends hard and reinforces. Do not trickle in.' }],
    },
    {
      key: 'green-10', title: 'Foundry Silence', theme: 'ashfall', size: 80, seed: 'protocol-10',
      story: ['The Foundry squats on the far side of the lava fields with every Bunker and squad it has left. The Foreman is inside.', 'The Collective brings the whole protocol: Wardens, Lenses, Rings, Halos, the Oracle, and a Nova.'],
      briefing: 'Full war against a living Foundry: destroy the Foundry.',
      epilogue: ['The Foundry cracks like a furnace door and the lava fields go dark. The Foreman is not among the dead; he never is.', 'Then, from the basin, a new hum: the Hive has bloomed, and it is coming.'],
      player: { faction: F, ore: 600, flux: 220 },
      enemy: fortified('red', 'normal', { structures: [{ key: 'post', at: 'point:5' }, { key: 'armory', at: [-5, -3] }] }),
      stages: [
        stage([obj('econ', 'capture', 'Hold 3 strategic points', { n: 3 }), obj('sanctum', 'build', 'Build the Sanctum', { key: 'sanctum', n: 1 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Foundry'), obj('loss', 'loseMax', 'Lose no more than 8 squads', { n: 8, optional: true })], 'A Nova outranges every Bunker. Screen it and let it roll.'),
      ],
      hints: [{ at: 'start', text: 'The Foundry will not wait. Two Bastions and a Pulse Ring at home while you expand.' }],
    },
    // ---------------- ACT III: The Bloom
    {
      key: 'green-11', title: 'Resonance', theme: 'verdant', size: 64, seed: 'protocol-11',
      story: ['The Verdant Basin, and the Swarm in full bloom: Dart packs by the dozen, too many to shoot, fast enough to reach the Lenses.', 'The Array hums and the Pulse Rings ring. Swarms that hear it forget why they came.'],
      briefing: 'Morale warfare: break swarms as they charge, and survive the bloom.',
      epilogue: ['The last swarm breaks a dozen paces from the Rings and scatters into the brush.', 'The Swarm has Kites now, and the Oracle has seen where they nest.'],
      player: { faction: F, ore: 520, flux: 150, structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'wardens', at: [3, 4] }, { key: 'lenses', at: [5, 2] }] },
      enemy: garrison('blue', { squads: [{ key: 'darts', at: 'point:3', n: 2 }, { key: 'needles', at: 'point:3' }], points: [3] }),
      waves: [wave(100, [{ key: 'darts', n: 2 }], { text: 'Swarm bloom, first wave.' }), wave(190, [{ key: 'darts', n: 3 }], { text: 'Second wave. Rings forward.' }), wave(280, [{ key: 'darts', n: 2 }, { key: 'wedges', n: 2 }], { text: 'Wedges: protect the Lenses.' }), wave(370, [{ key: 'darts', n: 3 }, { key: 'needles', n: 1 }, { key: 'wedges', n: 1 }], { text: 'Final bloom.' })],
      stages: [
        stage([obj('pulsers', 'train', 'Train 2 Pulse Rings', { key: 'pulsers', n: 2 })]),
        stage([obj('broken', 'broken', 'Break 6 swarm squads', { n: 6 }), obj('survive', 'survive', 'Survive the bloom (7 minutes)', { seconds: 430 }), obj('cap', 'capture', 'Hold 3 points', { n: 3 })], 'Pulse Rings deal little damage and a lot of morale. Break the swarms, then let the Wardens finish them.'),
        stage([obj('cap3', 'capture', 'Capture the swarm point', { rank: 3 }), obj('beacon', 'build', 'Build a Beacon on a captured point', { key: 'beacon', n: 1 })]),
      ],
      hints: [{ at: 'start', text: 'Pulse Rings are short-ranged. Put them in front, in cover, with Wardens beside them.' }],
    },
    {
      key: 'green-12', title: 'Kite Season', theme: 'ashfall', size: 64, seed: 'protocol-12',
      story: ['Kites over the lava, burning Siphons faster than they can be regrown. Nothing on the ground can catch them.', 'Bastions do not need to catch anything. They need the Kites to come close, and Kites always come close to Siphons.'],
      briefing: 'Air defence: protect your Siphons with Bastions and Lenses, kill the Kite wings, then burn the Spire they came from.',
      epilogue: ['Four Kite wings are shards on the lava. The Spire is next.', 'And then the Nest.'],
      player: { faction: F, ore: 650, flux: 240, structures: [{ key: 'array', at: [-4, 3] }, { key: 'siphon', at: 'ore:0' }, { key: 'siphon', at: 'ore:1' }], squads: [{ key: 'lenses', at: [3, 4], n: 2 }, { key: 'wardens', at: [5, 2] }] },
      enemy: war('blue', 'passive', { incomeMult: 0.9, structures: [{ key: 'spire', at: [4, -2] }, { key: 'lode', at: 'ore:6' }, { key: 'lode', at: 'ore:7' }, { key: 'thorn', at: [-3, 3] }], squads: [{ key: 'kites', at: 'point:4' }, { key: 'kites', at: 'point:5' }, { key: 'darts', at: [0, 5] }] }),
      waves: [wave(60, [{ key: 'kites', n: 1 }], { target: 'ore:0', text: 'Kites on your Siphon.' }), wave(180, [{ key: 'kites', n: 2 }], { target: 'ore:1', text: 'Two wings on the other vein.' })],
      stages: [
        stage([obj('bastion', 'build', 'Build 2 Bastions', { key: 'bastion', n: 2 }), obj('kites', 'kill', 'Destroy 4 Kite Wings', { key: 'kites', n: 4 })], 'Bastions beside the Siphons. Lenses for whatever gets past them.'),
        stage([obj('spire', 'destroy', 'Destroy the Spire', { key: 'spire', n: 1 }), obj('cap', 'capture', 'Hold 4 points', { n: 4 })]),
      ],
      hints: [{ at: 'start', text: 'Kites are vehicles: Lens beams and Bastion fire take them apart.' }],
    },
    {
      key: 'green-13', title: 'The Nest', theme: 'frost', size: 64, seed: 'protocol-13',
      story: ['The Nest breeds Wedges, and Wedges kill Lenses from behind faster than shields refill. It sits behind a Thorn line on the ice, defended by everything the Swarm is not currently using elsewhere.', 'The Oracle can see it. That is half the battle. The Nova is the other half.'],
      briefing: 'Assault: field a Nova Sphere and destroy the Nest and its Thorn line, against a Swarm that defends but does not attack.',
      epilogue: ['The Nest burns green on the ice. No more Wedges.', 'The Hive answers with the only thing it has left that outranges a Nova: nothing. It sends an Obelisk anyway.'],
      player: { faction: F, ore: 750, flux: 300, structures: [{ key: 'array', at: [-4, 3] }, { key: 'sanctum', at: [4, -3] }], squads: [{ key: 'wardens', at: [3, 4], n: 2 }, { key: 'pulsers', at: [5, 2] }, { key: 'halo', at: [2, 6] }] },
      enemy: war('blue', 'passive', { incomeMult: 1.0, structures: [{ key: 'nest', at: [4, -2] }, { key: 'thorn', at: [-3, -3] }, { key: 'thorn', at: [3, 3] }, { key: 'thorn', at: [0, 5] }, { key: 'lode', at: 'ore:6' }, { key: 'lode', at: 'ore:7' }], squads: [{ key: 'wedges', at: [0, 5], n: 2 }, { key: 'darts', at: [-3, 2], n: 2 }, { key: 'needles', at: [3, -4] }] }),
      stages: [
        stage([obj('nova', 'train', 'Field a Nova Sphere', { key: 'nova', n: 1 }), obj('econ', 'capture', 'Hold 3 points', { n: 3 })]),
        stage([obj('thorns', 'destroy', 'Destroy 3 Thorns', { key: 'thorn', n: 3 }), obj('nest', 'destroy', 'Destroy the Nest', { key: 'nest', n: 1 })], 'The Nova outranges Thorns. Rings beside it against the Wedges, and let it roll.'),
      ],
      hints: [{ at: 'start', text: 'Wedges hunt Lenses and Novas from behind. Keep Pulse Rings on the flanks.' }],
    },
    {
      key: 'green-14', title: 'Obelisk', theme: 'urban', size: 64, seed: 'protocol-14',
      story: ['An Obelisk walks down the main boulevard, lobbing shards that flatten Bastions and the shields behind them. It is slow. It does not need to be fast.', 'It has a minimum range. The Oracle has computed exactly where that is.'],
      briefing: 'Siege defence: survive an Obelisk assault on the city and kill the walkers inside their minimum range.',
      epilogue: ['Two Obelisks lie in the boulevard with Wardens standing on them.', 'The Hive has nothing left to send. The Oracle has its location.'],
      player: { faction: F, ore: 750, flux: 300, structures: [{ key: 'array', at: [-4, 3] }, { key: 'bastion', at: [6, 1] }], squads: [{ key: 'wardens', at: [3, 4], n: 2 }, { key: 'pulsers', at: [5, 2], n: 2 }, { key: 'oracle', at: [2, 2] }], points: [0, 1, 2] },
      enemy: garrison('blue', { points: [4, 5] }),
      waves: [wave(60, [{ key: 'darts', n: 3 }], { text: 'Swarm ahead of the walkers.' }), wave(150, [{ key: 'obelisk', n: 1 }, { key: 'darts', n: 2 }], { text: 'An Obelisk. Get close.' }), wave(270, [{ key: 'needles', n: 2 }, { key: 'wedges', n: 1 }], { text: 'Needles and Wedges: guard the Halo.' }), wave(380, [{ key: 'obelisk', n: 1 }, { key: 'darts', n: 3 }, { key: 'apex', n: 1 }], { text: 'The second Obelisk, and the Apex.' })],
      stages: [
        stage([obj('obelisks', 'kill', 'Destroy 2 Obelisks', { key: 'obelisk', n: 2, hint: 'Rush inside their minimum range.' }), obj('hold', 'hold', 'Hold 3 points for 7 minutes', { n: 3, seconds: 420 }), obj('loss', 'loseMax', 'Lose no more than 4 squads', { n: 4, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'The Oracle sees the Obelisk long before it fires. Move before the shell.' }],
    },
    {
      key: 'green-15', title: 'Hive', theme: 'crystal', size: 80, seed: 'protocol-15',
      story: ['The Hive squats on the dunes with every Thorn and swarm it has left. The Apex is inside.', 'The Sanctum raises every shield in the Collective. The Oracle has computed the answer. Deliver it.'],
      briefing: 'Full war against a living Swarm: destroy the Hive.',
      epilogue: ['The Hive collapses into itself, a pyramid of dark glass. The Swarm scatters across the dunes, dividing, dwindling.', 'For a moment the Lattice is quiet. Then the Foundry and the Swarm, both broken, find each other, and find a common enemy.'],
      player: { faction: F, ore: 650, flux: 240 },
      enemy: fortified('blue', 'normal', { incomeMult: 1.15, structures: [{ key: 'spire', at: [-5, -3] }, { key: 'claim', at: 'point:5' }] }),
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('nova', 'train', 'Field a Nova Sphere', { key: 'nova', n: 1 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Hive'), obj('loss', 'loseMax', 'Lose no more than 10 squads', { n: 10, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Swarms come fast and early. Two Pulse Rings and a Bastion will hold the door while you tech.' }],
    },
    // ---------------- ACT IV: The Coalition
    {
      key: 'green-16', title: 'Two Banners', theme: 'verdant', size: 64, seed: 'protocol-16',
      story: ['Swarm Thorns and Foundry Bunkers on the same ridge. The old enemies have decided the Collective is the newer problem.', 'The Oracle computed this outcome some time ago. It did not enjoy it.'],
      briefing: 'Mixed garrison: clear a ridge held by both Swarm and Foundry forces and take every point on it.',
      epilogue: ['The ridge falls. The two garrisons never learned to fight together, only to die together.', 'Both remaining strongholds are now sending everything they have.'],
      player: { faction: F, ore: 650, flux: 240, structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'wardens', at: [3, 4], n: 2 }, { key: 'pulsers', at: [5, 2] }, { key: 'lenses', at: [2, 6] }] },
      enemies: [garrison('blue', { structures: [{ key: 'thorn', at: 'point:2' }, { key: 'claim', at: 'point:2' }], squads: [{ key: 'darts', at: 'point:2', n: 2 }, { key: 'needles', at: 'point:2' }], points: [2] }), garrison('red', { structures: [{ key: 'bunker', at: 'point:4' }, { key: 'post', at: 'point:4' }], squads: [{ key: 'bolts', at: 'point:4' }, { key: 'hammers', at: 'point:4', order: 'hold' }], points: [4] })],
      stages: [
        stage([obj('kill', 'kill', 'Destroy 5 enemy squads', { n: 5 }), obj('posts', 'destroy', 'Destroy the Claim Spike and the Watch Post', { n: 2 })]),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 })]),
      ],
      hints: [{ at: 'start', text: 'Rings for the swarms, Lenses for the gun team. Never both at once.' }],
    },
    {
      key: 'green-17', title: 'Crossfire', theme: 'urban', size: 80, seed: 'protocol-17',
      story: ['The coalition attacks from both corners of the city at once, waves timed to arrive together, Kites over the roofs and Mortars behind.', 'The Collective has an Array, three points and eight minutes to prove that shields, given a breath, come back.'],
      briefing: 'Two-front defence: hold three points for eight minutes against alternating Swarm and Foundry waves.',
      epilogue: ['The city is quiet and the streets are full of triangles and squares.', 'Their economies are exposed. The Oracle has already mapped them.'],
      player: { faction: F, ore: 750, flux: 300, structures: [{ key: 'array', at: [-4, 3] }, { key: 'bastion', at: [6, 1] }, { key: 'bastion', at: [-6, -1] }], squads: [{ key: 'wardens', at: [3, 4], n: 2 }, { key: 'pulsers', at: [5, 2] }, { key: 'halo', at: [2, 6] }, { key: 'oracle', at: [2, 2] }], points: [0, 1, 2] },
      enemies: [garrison('blue', { points: [4] }), garrison('red', { points: [5] })],
      waves: [wave(60, [{ key: 'darts', n: 3 }], { owner: 1, text: 'Swarm from the north.' }), wave(120, [{ key: 'bolts', n: 2 }], { owner: 2, text: 'Foundry infantry from the south.' }), wave(200, [{ key: 'kites', n: 2 }, { key: 'wedges', n: 1 }], { owner: 1, text: 'Kites and Wedges.' }), wave(280, [{ key: 'hammers', n: 2 }, { key: 'breachers', n: 1 }], { owner: 2, text: 'Gun teams and Breachers.' }), wave(360, [{ key: 'obelisk', n: 1 }, { key: 'darts', n: 2 }], { owner: 1, text: 'An Obelisk.' }), wave(430, [{ key: 'crusher', n: 1 }, { key: 'mortar', n: 1 }, { key: 'bolts', n: 1 }], { owner: 2, text: 'Armour and artillery.' })],
      stages: [
        stage([obj('hold', 'hold', 'Hold 3 points for 8 minutes', { n: 3, seconds: 480 }), obj('loss', 'loseMax', 'Lose no more than 4 squads', { n: 4, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Keep the Halo central so both fronts are inside its ring.' }],
    },
    {
      key: 'green-18', title: 'Scorched Vein', theme: 'ashfall', size: 80, seed: 'protocol-18',
      story: ['Lode Burrows and Drill Rigs share the lava fields, guarded by Thorns and Bunkers. Two economies feeding two enemies.', 'The Oracle sends Lenses and a Halo with one instruction: nothing that pumps ore is to be left standing.'],
      briefing: 'Deep raid: destroy the extractors of both enemies without losing more than two squads.',
      epilogue: ['The lava fields are dark. Two economies starve at once.', 'Only the Hive stands between the Collective and the Prime Vein.'],
      player: { faction: F, ore: 700, flux: 300, structures: [{ key: 'array', at: [-4, 3] }], squads: [{ key: 'lenses', at: [3, 4], n: 2 }, { key: 'wardens', at: [5, 2], n: 2 }, { key: 'halo', at: [2, 6] }] },
      enemies: [war('blue', 'passive', { incomeMult: 0.9, structures: [{ key: 'lode', at: 'ore:6' }, { key: 'lode', at: 'ore:4' }, { key: 'thorn', at: 'ore:4' }], squads: [{ key: 'darts', at: 'ore:6' }] }), war('red', 'passive', { incomeMult: 0.9, structures: [{ key: 'drill', at: 'ore:7' }, { key: 'drill', at: 'ore:5' }, { key: 'bunker', at: 'ore:5' }], squads: [{ key: 'bolts', at: 'ore:7' }] })],
      stages: [
        stage([obj('lodes', 'destroy', 'Destroy 2 Lode Burrows', { key: 'lode', n: 2 }), obj('rigs', 'destroy', 'Destroy 2 Drill Rigs', { key: 'drill', n: 2 }), obj('loss', 'loseMax', 'Lose no more than 2 squads', { n: 2 })]),
      ],
      hints: [{ at: 'start', text: 'Both enemies rebuild. Hit fast, leave, and come back for what they rebuild.' }],
    },
    {
      key: 'green-19', title: 'The Anvil', theme: 'frost', size: 80, seed: 'protocol-19',
      story: ['The Hive has rebuilt on the ice with Foundry Bunkers at its gates and Hammer Teams in its swarms. It has learned everything.', 'So has the Oracle.'],
      briefing: 'Full war against a hardened Swarm with Foundry support: destroy the Hive.',
      epilogue: ['The Hive falls for the second and last time. The Foundry garrison surrenders the gates.', 'Beyond the ice the Prime Vein hums, and every faction that is left is marching toward it.'],
      player: { faction: F, ore: 700, flux: 280 },
      enemies: [fortified('blue', 'hard', { incomeMult: 1.15, structures: [{ key: 'spire', at: [-5, -3] }, { key: 'claim', at: 'point:5' }] }), garrison('red', { structures: [{ key: 'bunker', at: 'point:4' }, { key: 'post', at: 'point:4' }], squads: [{ key: 'bolts', at: 'point:4' }, { key: 'hammers', at: 'point:4', order: 'hold' }], points: [4] })],
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('sanctum', 'build', 'Build the Sanctum', { key: 'sanctum', n: 1 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Hive'), obj('loss', 'loseMax', 'Lose no more than 10 squads', { n: 10, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'The hard Swarm rushes early. Two Bastions and two Pulse Rings before anything else.' }],
    },
    // ---------------- FINALE
    {
      key: 'green-20', title: 'Prime Vein', theme: 'crystal', size: 80, seed: 'protocol-20',
      story: ['The Prime Vein lies open under the dunes, and around it, in three corners of the world, three peoples have built everything they have left.', 'The Swarm and the Foundry will fight each other as readily as the Collective. The Oracle does not mind. It computed this ending before the war began, and has only been waiting for the others to arrive.'],
      briefing: 'All-out war: two living enemies, both hard, on the largest battleground. Destroy both the Hive and the Foundry.',
      epilogue: ['The Hive falls. The Foundry falls. The Collective settles over the Prime Vein and begins, slowly, to think about what shape a world should be.', 'The Lattice will be reforged, in the shape that endures. Campaign complete.'],
      player: { faction: F, ore: 800, flux: 320 },
      enemies: [fortified('blue', 'hard', { incomeMult: 1.2, structures: [{ key: 'spire', at: [-5, -3] }] }), fortified('red', 'hard', { incomeMult: 1.2, points: [], structures: [{ key: 'armory', at: [-5, -3] }] })],
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('hero', 'hero', 'Field the Oracle')]),
        stage([obj('hqs', 'destroyHq', 'Destroy the Hive and the Foundry', { all: true }), obj('loss', 'loseMax', 'Lose no more than 15 squads', { n: 15, optional: true })], 'They will fight each other. Let them, then finish whoever wins.'),
      ],
      hints: [{ at: 'start', text: 'Three-way war: the two enemies attack each other too. Hold your corner, harvest, and strike the weaker one first.' }],
    },
  ],
};
