// Doctrine, chapters 6-40: the Iron Foundry's own story. Its goal is the Great Forge.
import { C, X } from './arc.js';

const BLUE_GATE = [{ faction: 'blue', hq: false, ai: null, structures: [{ key: 'thorn', at: 'point:4' }, { key: 'claim', at: 'point:4' }], squads: [{ key: 'darts', at: 'point:4', n: 2 }, { key: 'needles', at: 'point:4' }], points: [4] }];

export const RED_ARC = {
  goal: 'The Great Forge',
  backstory: 'The guild\'s oldest teaching is that the Lattice was not grown. It was forged, on an anvil at the Prime Vein, and the Forge still stands somewhere under the crystal. Every rig the Foundry sinks is looking for it, and every loss is written in the Foreman\'s ledger against the day it is found. Raise the Forge, feed it the Vein, and the Lattice can be struck whole again: one block, no fracture, nothing that divides and nothing that dreams. The Swarm calls it a cage. The Collective calls it a mistake. The Foreman calls it the Great Forge, and doctrine says it is raised over whoever stands in the way.',
  outcome: 'The Great Forge is raised beside the Prime Vein and the Foreman strikes the first blow. The Lattice is reforged in the shape that lasts: one block, riveted, and nothing will ever crack it again.',
  acts: [
    { title: 'Act I · Awakening', from: 0 }, { title: 'Act II · The Ledger', from: 5 }, { title: 'Act III · Iron and Glass', from: 10 },
    { title: 'Act IV · Built Under Fire', from: 15 }, { title: 'Act V · Salvage', from: 20 }, { title: 'Act VI · Accords', from: 25 },
    { title: 'Act VII · The Ninth Bunker', from: 30 }, { title: 'Act VIII · The Great Forge', from: 35 },
  ],
  chapters: [
    // ---- Act II · The Ledger (6-10): the Swarm comes for the drill fields, and the ledger opens.
    X('greywater', 2),
    C('Rivet Bridge', 'verdant', 64, 2, 'escort', { rival: 'blue' },
      ['The rebuilt Works has one Crusher Tank to its name, and the Foreman wants it on the far bank of the Greywater where the Swarm is nesting. There is no bridge. There is a road, and the road is full of Darts.', 'The tank is slow. Doctrine says slow is fine, as long as it arrives.'],
      'Escort duty: bring the Crusher Tank down the river road through swarm ambushes to the far outpost.',
      ['The tank reaches the outpost with blades stuck in its plating and starts firing before it stops.', 'The Ashfall drill fields are next, and the Swarm has found them too.']),
    X('drillfields', 2),
    C('Burrow Hunt', 'crystal', 64, 3, 'raid', { rival: 'blue', n: 4 },
      ['Lode Burrows on every vein in the dunes, each one feeding the Hive, each one dug deeper than any rig the guild has ever sunk. The deepest of them is under a Nest, and the ground around it hums.', 'The Foreman wants them gone. A Hive that cannot eat cannot divide, and a Burrow that deep is digging toward something the guild has been looking for since before the fracture.'],
      'Deep raid: destroy four Lode Burrows without losing more than two squads.',
      ['Four Burrows are craters. The Nest survived; the ledger notes it.', 'The Hive\'s hum falters, then comes back louder, and it is coming down the Salt Road.']),
    C('The Salt Road', 'frost', 64, 3, 'tugOfWar', { rival: 'blue' },
      ['The Salt Road runs outpost to outpost across the ice, from the Foundry camp to the Swarm\'s Nest. Every outpost the Foundry takes brings iron up the road behind it.', 'Doctrine says advance in steps. The Foreman has never been in a hurry.'],
      'Tug-of-war: push down the Salt Road outpost by outpost; each one taken brings reinforcements.',
      ['The Nest at the end of the road burns. The Swarm falls back into a crystal quarry.', 'The Foundry follows, slowly, with the guns.']),
    C('The Quarry', 'crystal', 64, 3, 'siege', { rival: 'blue' },
      ['The Swarm has turned a crystal quarry into a fortress: Thorns on every ridge, Claim Spikes on every point, canyon walls between. In the bottom of it, the Hive is growing something tall.', 'The Works sends up Crusher Tanks and Mortar Blocks. Walls are a temporary condition.'],
      'Siege: field armour and artillery and dismantle the quarry\'s defences without charging the guns.',
      ['The quarry is craters and glass. The Swarm scatters into the canyons with its Obelisk.', 'To the east the Collective has woken fully, and the guild\'s scouts say it has been building Bastions on the ice for months. Watching.']),
    // ---- Act III · Iron and Glass (11-15): the Collective, which has been watching, finally answers.
    X('glasslake', 3),
    X('halo', 4),
    C('Beacon Hill', 'urban', 64, 4, 'siege', { rival: 'green' },
      ['Beacons on every point of the Ruined City, Bastions beside them. The Collective can see the whole city, and its beams reach anything it sees.', 'The Foreman\'s answer is the oldest: shells that fall from beyond sight.'],
      'Siege: field armour and Mortars and destroy the Beacons and Bastions from cover.',
      ['The city goes blind, block by block. The Collective pulls back behind its Halos.', 'The Foundry will have to kill the rings before it can kill anything else, and the Collective has rolled out something larger than rings.']),
    C('Iron Rain', 'ashfall', 64, 4, 'countdown', { rival: 'green', minutes: 9, waves: 6 },
      ['The Collective\'s Novas have the Foundry\'s forward base under the longest guns in the Lattice. Relief is coming from the Works, nine minutes away, with Mortars.', 'Nine minutes under stars. The Foreman writes the time in the ledger and starts the clock.'],
      'Survive the countdown: hold the forward base under Nova bombardment until relief arrives, then counter-attack.',
      ['The relief column arrives with Mortars and the Novas learn what it is to be outranged.', 'Under the craters, the ground has begun to glow. The guild\'s deepest rig went down three hundred metres last week, and the Foreman has begun to wonder.']),
    // ---- Act IV · Built Under Fire (16-20): the Bleed rises, and the Foundry rebuilds the only way it knows.
    X('bleed', 4),
    C('The Walled City', 'urban', 64, 4, 'chokepoint', { rival: 'blue' },
      ['The Ruined City is the Foundry\'s refuge from the Bleed, and it has one gate the Swarm can reach. The Foreman puts everything at the gate.', 'A wall is only a wall until a Breacher arrives. The Swarm does not have Breachers.'],
      'Chokepoint defence: hold the city gate with Bunkers and gun teams against the swarm tide.',
      ['The gate holds. The Swarm goes looking for another way in, and there is none.', 'The Collective has taken the Ashfall behind the city. The Foundry is boxed in, and doctrine says a box is a thing you break out of.']),
    C('Ashfall Line', 'ashfall', 64, 5, 'holdTheLine', { rival: 'green', minutes: 10, points: 3, waves: 7 },
      ['The Foundry has broken out of the city into the Ashfall and holds three points on the craters. The Collective wants the crossing behind them.', 'Ten minutes, three points, seven waves. Doctrine.'],
      'Hold the line: keep three points on the Ashfall for ten minutes against Collective waves.',
      ['The craters are full of glass and the Foundry has not moved.', 'The Collective is pushing on two roads now, at two Works. The Foreman cannot be in two places. The doctrine can.']),
    C('Two Works', 'frost', 64, 5, 'multiFront', { rival: 'green' },
      ['The Foundry has two bases on the ice, far apart, and the Collective is pushing both. Two Works, two armies, one Foreman.', 'He cannot be in two places. The doctrine can.'],
      'Multi-front: hold both bases against Collective pushes, then destroy the Collective forward base.',
      ['Both bases hold. The Collective forward base is a crater.', 'The winter is ending. The Foundry has one push left in it, and the Foreman intends to make it count.']),
    C('The Winter Push', 'urban', 80, 5, 'war', { rival: 'green' },
      ['The Foreman\'s winter push: everything the Foundry rebuilt, thrown at the Collective\'s Core in the ruins before the Bleed reaches it too.', 'There is no trick left. There is only doctrine.'],
      'Full war against a living Collective: destroy the Core in the ruins.',
      ['The shield fails. The Core cracks like an egg.', 'Then the Bleed comes for the ruins too, and the Foundry with them.']),
    // ---- Act V · Salvage (21-25): the Foundry is ash. Doctrine says rebuild. It does not say with what.
    C('Ashes', 'ashfall', 64, 5, 'commando', { rival: 'blue', target: 'prod' },
      ['The Foundry is ash and the Foreman is walking out of it with a Breacher squad and a gun team. The Swarm has a Nest in the craters.', 'A Nest is a door. The Foreman has a hammer.'],
      'Commando: with no base, infiltrate the Swarm\'s Nest in the ash with the Foreman, destroy it, and escape.',
      ['The Nest burns and the Foreman walks out of the ash with both squads.', 'Somewhere in the craters, stranded Foundry squads are waiting for orders. He has some.']),
    X('scavenge', 5),
    C('The Engine', 'frost', 64, 5, 'escort', { rival: 'green' },
      ['The scavenged Crusher is carrying something the Bleed threw up out of the crystal: a block of worked iron older than the guild, riveted in a pattern no Works has ever cut. The Foreman calls it the Engine. He thinks it is a piece of the Forge.', 'It is on the wrong side of the ice, and the Collective has computed what it is.'],
      'Escort duty: bring the Crusher Tank and the Engine across the ice through Collective ambushes to the far outpost.',
      ['The tank arrives with beam scars from nose to tail, and the Engine is intact.', 'The Collective\'s new base is a fortress. It is fed by a road, and roads can be cut.']),
    C('Starve the Core', 'urban', 64, 5, 'interdiction', { rival: 'green' },
      ['The Collective fortress in the ruins cannot be stormed: Bastions on every approach, the Oracle inside. It is fed by convoys from the far Siphons.', 'The Foreman has starved better places.'],
      'Supply interdiction: ambush the Collective convoys and burn the Siphons, then break the starving fortress.',
      ['The convoys stop and the Bastions go dark one by one.', 'The frozen river is the last line between the Foundry and the Collective heartland.']),
    C('The Crossing', 'frost', 64, 6, 'tugOfWar', { rival: 'green' },
      ['The frozen river has five outposts along it, Collective on every one. The Foundry takes them one step at a time, and iron follows each step.', 'The Foreman has never been in a hurry.'],
      'Tug-of-war: push across the frozen river outpost by outpost; each one taken brings reinforcements.',
      ['The far bank is Foundry. The Collective\'s Array on it is dark.', 'On the far bank, the Swarm and the Collective have made a pact. The Foundry heartland is the first thing they agree on.']),
    // ---- Act VI · Accords (26-30): doctrine has a chapter on pacts. The Foreman wrote the minute into it himself.
    X('glasspact', 6),
    X('ironaccord', 6),
    X('shearpact', 6),
    X('betrayal', 6),
    C('The Reckoning', 'crystal', 80, 6, 'war', { rival: 'green' },
      ['The Collective\'s betrayal has a price. The Foundry goes to collect it at the Core\'s dune fortress with everything it has.', 'There will be no more accords. The Forge is raised by one hand.'],
      'Full war: destroy the Core at its dune fortress.',
      ['The Core falls. The Oracle\'s light goes out across the sand.', 'The Swarm and the Collective have both learned the same lesson about the Foundry. They will learn it together.']),
    // ---- Act VII · The Ninth Bunker (31-35): the other two peoples unite against the Forge.
    C('Two Banners', 'verdant', 64, 7, 'twoBanners', { r1: 'blue', r2: 'green' },
      ['Swarm Thorns and Collective Bastions on the same ridge. The old enemies have decided the Foundry is the newer problem.', 'The Foreman finds this reasonable. He would have done the same.'],
      'Mixed garrison: clear a ridge held by both Swarm and Collective forces and take every point on it.',
      ['The ridge falls. The two garrisons never learned to fight together, only to die together.', 'Both strongholds are now sending everything they have, timed to arrive at once.']),
    C('The Ninth Bunker', 'urban', 80, 7, 'crossfire', { r1: 'blue', r2: 'green', minutes: 9 },
      ['The coalition attacks from both corners of the city at once, Kites over the roofs and Novas behind. Doctrine says eight Bunkers hold a city.', 'The Foreman builds a ninth, and gives the Foundry three points and nine minutes to remind everyone what it is for.'],
      'Two-front defence: hold three points for nine minutes against alternating Swarm and Collective waves.',
      ['The city is quiet and the streets are full of Swarm and Collective dead.', 'Their economies are exposed. The Foreman intends to make that permanent.']),
    C('Scorched Vein', 'ashfall', 80, 7, 'raid', { rival: 'green', n: 4 },
      ['Lode Burrows and Siphons share the lava fields, guarded by Thorns and Bastions. Two economies feeding two enemies.', 'The Foreman sends the tanks with one instruction: nothing that pumps ore is to be left standing.'],
      'Deep raid: destroy four coalition extractors on the lava fields without losing more than two squads.',
      ['The lava fields are dark. Two economies starve at once.', 'Only the Collective\'s canyon fortress stands between the Foundry and the Prime Vein, and it stands on the site the guild calls the Anvil.']),
    C('The Anvil', 'crystal', 80, 7, 'war', { rival: 'green', extraEnemies: BLUE_GATE },
      ['The Collective has rebuilt in the canyons with Swarm Thorns at its gates, on the one place in the Lattice the guild\'s oldest maps mark with a hammer. It has learned everything.', 'So has the Foreman. And he has the Engine.'],
      'Full war against a hardened Collective with Swarm support at its gates: destroy the Core.',
      ['The Core falls for the last time. The Swarm garrison scatters from the gates.', 'Under the canyon floor, the Engine hums against something that answers it. The Forge is close.']),
    C('The Approaches', 'crystal', 64, 7, 'protectVip', { rival: 'blue', ranks: [1, 2, 3] },
      ['The approaches to the Prime Vein are three points on a ridge, and the Swarm holds them. The Foreman must take them himself; the Foundry will not advance without him.', 'The Swarm knows. Every Wedge on the ridge is looking for him.'],
      'Protect the VIP: keep the Foreman alive while he leads the capture of the three approach points.',
      ['Three points, and the Foreman still standing on the last of them.', 'The Vein is in sight. It glows, and the Engine glows back.']),
    // ---- Act VIII · The Great Forge (36-40): the end of the world, the Foundry's way.
    C('The Outer Ring', 'crystal', 80, 8, 'resourceRace', { rival: 'blue', quota: 3000, minutes: 15 },
      ['The Outer Ring of the Prime Vein is the richest ore in the Lattice, and the Swarm is eating it as fast as the Foundry can drill.', 'The Forge will need every ton of it. Whoever has more when the Bleed returns wins the war before it starts.'],
      'Resource race: own the Outer Ring veins and stockpile three thousand ore before the Swarm does.',
      ['The stockpile is full. The Works has never run so hot.', 'And the ground under it is glowing again.']),
    X('bleedreturns', 8),
    C('Last Crusher', 'crystal', 80, 8, 'escort', { rival: 'blue' },
      ['The last Crusher in the world rolls from the Works to the centre with the Engine on its back, and both other peoples want it dead before it arrives.', 'It arrives, or the Forge is never raised.'],
      'Escort duty: bring the last Crusher Tank and the Engine to the centre through swarm ambushes.',
      ['The tank stands at the centre of the world with the Foundry around it, and the Engine is set down on the seam.', 'The other two armies are already there, in their corners, building.']),
    X('threecorners', 8),
    C('The Great Forge', 'crystal', 80, 8, 'finale', {
      r1: 'blue', r2: 'green',
      goal: [{ id: 'forge', type: 'buildNear', text: 'Raise the Great Forge: build an Armory beside the Prime Vein', key: 'armory', at: 'center', radius: 14, n: 1 }, { id: 'hold', type: 'hold', text: 'Hold five points for two minutes while it is raised', n: 5, seconds: 120 }],
      goalIntro: 'Both of them are broken. The seam is open. Raise the Forge over it and hold the ground while it is built.',
    },
      ['The Prime Vein lies open under the dunes, and around it, in three corners of the world, three peoples have built everything they have left. The Swarm wants to be it. The Collective wants to still it.', 'The Foundry wants to forge it. The Engine is on the seam and the ledger is open at its last page, and the Foreman will have to go through both of them.'],
      'The finale: destroy both the Hive and the Core, then raise the Great Forge beside the Vein and hold the ground.',
      ['The Hive falls. The Core falls. The Great Forge is raised beside the Prime Vein and the Foreman strikes the first blow.', 'The Lattice is reforged in the shape that lasts. One block, riveted, and nothing will ever crack it again. Campaign complete.'],
      [{ at: 'stage:2', text: 'The Armory must stand within reach of your structures. Fortify the point nearest the seam with a Watch Post first, then build beside it.' }]),
  ],
};
