// Campaign: Doctrine (Iron Foundry). Twenty chapters in four acts.
import { garrison, war, obj, stage, wave, fortified } from './common.js';

const F = 'red';
export const RED = {
  faction: F, title: 'Doctrine', tagline: 'Hold. Suppress. Breach. Rebuild.',
  intro: 'The Foundry does not bloom and it does not flow. It holds ground, one riveted square at a time, and it does not give ground back. The Foreman\'s guild has one teaching: everything that lasts was built under fire.',
  acts: [{ title: 'Act I · The Line', from: 0 }, { title: 'Act II · Swarm Season', from: 5 }, { title: 'Act III · Glass and Iron', from: 10 }, { title: 'Act IV · The Coalition', from: 15 }, { title: 'Finale', from: 19 }],
  chapters: [
    // ---------------- ACT I
    {
      key: 'red-1', title: 'Hold the Line', theme: 'urban', size: 48, seed: 'doctrine-1',
      story: ['A single Foundry, fresh from the forge, on the edge of the Ruined City. The Swarm has already found it: Dart packs are coming down the boulevards in waves.', 'You have walls, rubble, and Bolt Squads. That is all a Foundry has ever needed.'],
      briefing: 'Learn the basics: train Bolt Squads, hold position in cover, survive the swarm waves and claim a point.',
      epilogue: ['The swarm breaks on the walls, three times. The street is carpeted with blue shards and not one Bolt Squad has moved.', 'The Foreman sends word: the swarms are being driven from the Verdant Basin. Go there. Bring the heavy guns.'],
      player: { faction: F, ore: 320, flux: 60, units: ['bolts'], buildings: ['drill'] },
      enemy: garrison('blue', { squads: [{ key: 'darts', at: 'point:2' }], points: [2] }),
      waves: [wave(75, [{ key: 'darts', n: 1 }], { text: 'Dart Swarm inbound. Hold.' }), wave(140, [{ key: 'darts', n: 2 }], { text: 'Two swarms. Stay in cover.' }), wave(210, [{ key: 'darts', n: 2 }, { key: 'needles', n: 1 }], { text: 'Last wave. Hold the line.' })],
      stages: [
        stage([obj('train', 'train', 'Train 2 Bolt Squads', { key: 'bolts', n: 2, hint: 'Tap the Foundry, then Bolt Squad.' }), obj('drill', 'build', 'Build a Drill Rig on an ore vein', { key: 'drill', n: 1 })]),
        stage([obj('cover', 'cover', 'Take 10 hits while in cover', { n: 10, hint: 'The blue shield icon over a squad means cover is working.' }), obj('survive', 'survive', 'Survive the swarm waves', { seconds: 260 })], 'Swarms are coming. Put your squads behind walls or in rubble and order Hold. Cover halves the damage.'),
        stage([obj('cap', 'capture', 'Capture the nearest strategic point', { rank: 0 }), obj('kill', 'kill', 'Destroy the swarm holding the second point', { n: 1 }), obj('cap2', 'capture', 'Capture the second point', { rank: 2 })], 'The street is yours. Take the point.'),
      ],
      hints: [{ at: 'start', text: 'Bolt Squads are heavy infantry: slow, tough, good against light infantry.' }, { at: 'stage:1', text: 'Select a squad and tap Hold so it does not chase into the open.' }],
    },
    {
      key: 'red-2', title: 'Suppressing Fire', theme: 'verdant', size: 48, seed: 'doctrine-2',
      story: ['The Verdant Basin, thick with brush and swarms. Rifles cannot kill triangles faster than the Hive makes them.', 'But a Hammer Team does not need to kill. Set up, and it pins a whole squad in place, breaks its morale, and leaves it helpless for the Bolts to finish.'],
      briefing: 'Suppression: build Hammer Teams, set them up, and break swarms before they reach you. Reinforce in the field.',
      epilogue: ['The basin is quiet. Broken swarms flee in every direction and do not come back.', 'The Foreman\'s next order is a map of the Ruined City, with the Swarm\'s new Claim Spikes marked in red.'],
      player: { faction: F, ore: 450, flux: 90, units: ['bolts', 'hammers'], buildings: ['drill', 'bunker'], squads: [{ key: 'bolts', at: [3, 4] }] },
      enemy: garrison('blue', { squads: [{ key: 'darts', at: 'point:1', n: 2 }, { key: 'darts', at: 'point:3', n: 2 }, { key: 'needles', at: 'point:3' }], points: [1, 3] }),
      waves: [wave(120, [{ key: 'darts', n: 2 }], { from: 'point:3', target: 'point:0', text: 'Swarm inbound on your point. Guns up.' }), wave(240, [{ key: 'darts', n: 2 }, { key: 'wedges', n: 1 }], { from: 'point:3', target: 'point:0', text: 'Wedges: they will try to get behind the guns.' })],
      stages: [
        stage([obj('hammers', 'train', 'Train 2 Hammer Teams', { key: 'hammers', n: 2 }), obj('setup', 'setup', 'Set up a Hammer Team (stand still until the ▣ icon shows)', { hint: 'Hammers cannot fire while moving. Give them a moment.' })]),
        stage([obj('broken', 'broken', 'Break 4 enemy squads', { n: 4 }), obj('cap', 'capture', 'Capture the nearest point', { rank: 0 }), obj('reinf', 'reinforce', 'Reinforce a squad twice', { n: 2 })], 'Guns forward, Bolts on their flanks. Break the swarms as they come.'),
        stage([obj('cap1', 'capture', 'Capture the swarm point', { rank: 1 }), obj('cap3', 'capture', 'Capture the far point', { rank: 3 })], 'Clear the basin.'),
      ],
      hints: [{ at: 'start', text: 'Hammer Teams have a narrow firing arc and a long range. Face them down the road.' }],
    },
    {
      key: 'red-3', title: 'Breach', theme: 'urban', size: 64, seed: 'doctrine-3',
      story: ['The Swarm has fortified the Ruined City: Claim Spikes on the points, Thorns in the windows, and every alley walled off. Walls do not care about rifles.', 'The Iron Works opens. Breachers come out with hammers the size of doors. A wall is only a wall until a Breacher arrives.'],
      briefing: 'Demolition: build the Iron Works, raise Breachers, knock down walls, destroy the Claim Spike, retake the point.',
      epilogue: ['The Spike shatters; the point is Foundry ground again. The Swarm pulls back through gaps that did not exist an hour ago.', 'The Foreman orders armour forward. The Swarm has Spires now, and things that fly.'],
      player: { faction: F, ore: 520, flux: 130, units: ['bolts', 'hammers', 'breachers'], buildings: ['drill', 'works', 'bunker', 'post'], squads: [{ key: 'bolts', at: [3, 4] }, { key: 'hammers', at: [5, 2] }] },
      enemy: garrison('blue', { structures: [{ key: 'claim', at: 'point:2' }, { key: 'thorn', at: 'point:2' }, { key: 'claim', at: 'point:4' }], squads: [{ key: 'darts', at: 'point:2' }, { key: 'needles', at: 'point:2' }, { key: 'darts', at: 'point:4', n: 2 }], points: [2, 4] }),
      stages: [
        stage([obj('works', 'build', 'Build the Iron Works', { key: 'works', n: 1 }), obj('breach', 'train', 'Train 2 Breacher squads', { key: 'breachers', n: 2 })]),
        stage([obj('walls', 'terrain', 'Destroy 4 wall or rock cells', { n: 4 }), obj('spike', 'destroy', 'Destroy a Claim Spike', { key: 'claim', n: 1 }), obj('cap', 'capture', 'Capture the point behind it', { rank: 2 })], 'Breachers smash cover around whatever they hit. Use them to open the walls, then storm through.'),
        stage([obj('post', 'build', 'Build a Watch Post on a captured point', { key: 'post', n: 1 }), obj('cap4', 'capture', 'Hold 3 strategic points', { n: 3 })], 'Fortify what you take.'),
      ],
      hints: [{ at: 'start', text: 'Breachers are melee. Keep Hammers behind them to pin defenders while they work.' }],
    },
    {
      key: 'red-4', title: 'Iron Column', theme: 'ashfall', size: 64, seed: 'doctrine-4',
      story: ['The Swarm has grown Kites, and the Ashfall rigs are burning. Nothing on foot can catch a Kite. A Crusher Tank does not have to: it makes the Kites come to it.', 'The Foreman\'s doctrine for armour is simple. The tank goes first. Everything else goes next to the tank.'],
      briefing: 'Armour: field a Crusher Tank, escort it with Bolts, and roll up the Swarm\'s forward Thorns and Kites.',
      epilogue: ['Two Thorns and a Kite wing are scrap on the lava. The column did not stop once.', 'The Foreman himself is coming to the front. He wants to see the ice before the Collective does.'],
      player: { faction: F, ore: 600, flux: 170, units: ['bolts', 'hammers', 'breachers', 'crusher'], buildings: ['drill', 'works', 'bunker', 'post'], structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }] },
      enemy: garrison('blue', { structures: [{ key: 'thorn', at: 'point:2' }, { key: 'thorn', at: 'point:4' }, { key: 'lode', at: 'ore:4' }, { key: 'claim', at: 'point:4' }], squads: [{ key: 'kites', at: 'point:4' }, { key: 'darts', at: 'point:2', n: 2 }, { key: 'needles', at: 'point:4' }], points: [2, 4] }),
      stages: [
        stage([obj('tank', 'train', 'Build a Crusher Tank', { key: 'crusher', n: 1 })]),
        stage([obj('thorns', 'destroy', 'Destroy 2 Thorns', { key: 'thorn', n: 2 }), obj('kites', 'kill', 'Destroy the Kite Wing', { key: 'kites', n: 1 }), obj('cap', 'capture', 'Hold 4 points', { n: 4 })], 'The tank in front, Bolts beside it, Hammers behind. Move as one.'),
      ],
      hints: [{ at: 'start', text: 'Kites are vehicles: Hammer Teams barely scratch them. Let the tank\'s blast and the Bolts do it.' }],
    },
    {
      key: 'red-5', title: 'The Foreman', theme: 'frost', size: 64, seed: 'doctrine-5',
      story: ['Frostbite. The Swarm has Claim Spikes on the passes and is pouring Wedges through them at anything that moves.', 'The Foreman takes the field. Where he walks, iron mends: nearby squads take less damage, and tanks and bunkers repair themselves under fire.'],
      briefing: 'Hero and defence: train the Foreman, attach him, build Bunkers, and hold four points against the Swarm.',
      epilogue: ['The Wedges break on repaired bunkers and reforming squads, then stop coming.', 'The Foreman looks east across the ice, at nothing yet. He does not like the quiet.'],
      player: { faction: F, ore: 650, flux: 200, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'bolts', at: [3, 4] }, { key: 'hammers', at: [5, 2] }] },
      enemy: war('blue', 'normal', { incomeMult: 0.95, structures: [{ key: 'claim', at: 'point:4' }, { key: 'claim', at: 'point:5' }, { key: 'thorn', at: [-3, 3] }, { key: 'nest', at: [4, -2] }], squads: [{ key: 'darts', at: [0, 5] }, { key: 'wedges', at: [-3, 2] }] }),
      stages: [
        stage([obj('hero', 'hero', 'Train the Foreman'), obj('attach', 'attach', 'Attach the Foreman to a squad'), obj('bunker', 'build', 'Build 2 Bunkers', { key: 'bunker', n: 2 })]),
        stage([obj('hold', 'hold', 'Hold 4 points for 2 minutes', { n: 4, seconds: 120 }), obj('kill', 'kill', 'Destroy 6 Swarm squads', { n: 6 })], 'Now hold. Four points, two minutes, whatever they send.'),
      ],
      hints: [{ at: 'start', text: 'The Foreman\'s repair aura heals vehicles and structures. Park him next to the Bunkers.' }],
    },
    // ---------------- ACT II: Swarm Season
    {
      key: 'red-6', title: 'Steel Rain', theme: 'verdant', size: 64, seed: 'doctrine-6',
      story: ['The Swarm has Spiked every point in the basin and put a Thorn beside each Spike. Rifles cannot reach them. Tanks can, but the Thorns shred the escort.', 'The Works produces the Mortar Block. Its shells fall from further than a Thorn can see.'],
      briefing: 'Artillery: field Mortar Blocks, shell the Spikes and Thorns from beyond their reach, and retake the basin.',
      epilogue: ['The basin is craters and splinters. The Swarm has no points left on this side of the river.', 'It answers the only way it knows: by dividing.'],
      player: { faction: F, ore: 600, flux: 200, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }, { key: 'hammers', at: [5, 2] }] },
      enemy: garrison('blue', { structures: [{ key: 'claim', at: 'point:2' }, { key: 'thorn', at: 'point:2' }, { key: 'claim', at: 'point:3' }, { key: 'thorn', at: 'point:3' }, { key: 'claim', at: 'point:4' }, { key: 'thorn', at: 'point:4' }], squads: [{ key: 'darts', at: 'point:2' }, { key: 'needles', at: 'point:3' }, { key: 'darts', at: 'point:4' }], points: [2, 3, 4] }),
      stages: [
        stage([obj('mortar', 'train', 'Build 2 Mortar Blocks', { key: 'mortar', n: 2 })]),
        stage([obj('thorns', 'destroy', 'Destroy 3 Thorns', { key: 'thorn', n: 3 }), obj('spikes', 'destroy', 'Destroy 3 Claim Spikes', { key: 'claim', n: 3 })], 'Set the mortars up outside Thorn range with Bolts in front. Let the shells fall.'),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 })]),
      ],
      hints: [{ at: 'start', text: 'Mortars have a minimum range. Anything that reaches them kills them; keep Hammers close.' }],
    },
    {
      key: 'red-7', title: 'Burrows', theme: 'crystal', size: 64, seed: 'doctrine-7',
      story: ['Lode Burrows on every vein in the dunes, each feeding the Hive. The Swarm does not defend them; it simply grows more.', 'The Foreman wants them gone anyway. A Hive that cannot eat cannot divide.'],
      briefing: 'Raid: destroy the Swarm\'s Lode Burrows across the dunes without losing more than two squads.',
      epilogue: ['Five Burrows collapse. The Hive\'s hum falters.', 'When it recovers it is louder, and it is coming for the Foundry.'],
      player: { faction: F, ore: 600, flux: 200, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'crusher', at: [3, 4] }, { key: 'bolts', at: [5, 2], n: 2 }, { key: 'breachers', at: [2, 6] }] },
      enemy: war('blue', 'passive', { incomeMult: 0.9, structures: [{ key: 'lode', at: 'ore:6' }, { key: 'lode', at: 'ore:7' }, { key: 'lode', at: 'ore:4' }, { key: 'lode', at: 'ore:5' }, { key: 'lode', at: 'ore:3' }, { key: 'thorn', at: 'ore:4' }], squads: [{ key: 'darts', at: 'ore:5' }, { key: 'needles', at: 'ore:3' }] }),
      stages: [
        stage([obj('lodes', 'destroy', 'Destroy 5 Lode Burrows', { key: 'lode', n: 5 }), obj('loss', 'loseMax', 'Lose no more than 2 squads', { n: 2 })]),
      ],
      hints: [{ at: 'start', text: 'The Swarm rebuilds Burrows. Hit the far ones first; the near ones you can hold.' }],
    },
    {
      key: 'red-8', title: 'Swarm Season', theme: 'urban', size: 64, seed: 'doctrine-8',
      story: ['The Hive has bloomed. Every street in the city is triangles, in waves that do not end, with Kites over the rooftops and an Obelisk somewhere behind.', 'The Foreman gives the order the Foundry was built for: hold.'],
      briefing: 'Grand defence: hold three points for nine minutes against the full Swarm, Obelisk included.',
      epilogue: ['The Obelisk dies in the main street with a Mortar shell through its crown. The bloom ends.', 'The Swarm has a Nest and a Spire somewhere north of the river. The Foreman intends to find them.'],
      player: { faction: F, ore: 750, flux: 300, structures: [{ key: 'works', at: [-4, 3] }, { key: 'bunker', at: [6, 1] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }, { key: 'hammers', at: [5, 2], n: 2 }, { key: 'foreman', at: [2, 2] }], points: [0, 1, 2] },
      enemy: garrison('blue', { points: [4, 5] }),
      waves: [wave(60, [{ key: 'darts', n: 3 }], { text: 'Swarm wave one.' }), wave(140, [{ key: 'darts', n: 2 }, { key: 'wedges', n: 2 }], { text: 'Wedges: guard the gun teams.' }), wave(220, [{ key: 'kites', n: 2 }, { key: 'darts', n: 2 }], { text: 'Kites over the rooftops.' }), wave(300, [{ key: 'needles', n: 2 }, { key: 'darts', n: 3 }], { text: 'Needles: keep the tank back.' }), wave(390, [{ key: 'obelisk', n: 1 }, { key: 'darts', n: 3 }, { key: 'apex', n: 1 }], { text: 'The Obelisk, and the Apex with it.' }), wave(480, [{ key: 'darts', n: 4 }, { key: 'wedges', n: 2 }], { text: 'The last bloom.' })],
      stages: [
        stage([obj('hold', 'hold', 'Hold 3 points for 9 minutes', { n: 3, seconds: 540 }), obj('broken', 'broken', 'Break 8 swarm squads', { n: 8 }), obj('loss', 'loseMax', 'Lose no more than 4 squads', { n: 4, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Two Hammer Teams covering one street, Bolts in cover ahead of them, the Foreman beside the tank.' }],
    },
    {
      key: 'red-9', title: 'The Nest', theme: 'verdant', size: 64, seed: 'doctrine-9',
      story: ['North of the river: a Nest and a Spire, breeding the Wedges and Kites that have plagued the Foundry all season. The Swarm defends them with everything that is not currently attacking.', 'Breachers to the walls, Mortars to the Thorns, tanks to the Nest.'],
      briefing: 'Assault: destroy the Swarm\'s Nest and Spire behind their Thorn line, against an enemy that defends but does not attack.',
      epilogue: ['The Nest burns green and the Spire folds. No more Wedges. No more Kites.', 'The Hive itself is all that remains, and the Foreman knows where it is.'],
      player: { faction: F, ore: 700, flux: 260, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }, { key: 'breachers', at: [5, 2] }, { key: 'mortar', at: [2, 6] }] },
      enemy: war('blue', 'passive', { incomeMult: 1.0, structures: [{ key: 'nest', at: [4, -2] }, { key: 'spire', at: [-4, 3] }, { key: 'thorn', at: [-3, -3] }, { key: 'thorn', at: [3, 3] }, { key: 'lode', at: 'ore:6' }, { key: 'lode', at: 'ore:7' }], squads: [{ key: 'darts', at: [0, 5], n: 2 }, { key: 'needles', at: [-3, 2] }, { key: 'wedges', at: [3, -4] }] }),
      stages: [
        stage([obj('econ', 'capture', 'Hold 3 points', { n: 3 })]),
        stage([obj('nest', 'destroy', 'Destroy the Nest', { key: 'nest', n: 1 }), obj('spire', 'destroy', 'Destroy the Spire', { key: 'spire', n: 1 })], 'Mortars strip the Thorns first. Then the tanks go in.'),
      ],
      hints: [{ at: 'start', text: 'The Swarm will not attack, but it defends hard and reinforces. Do not trickle in.' }],
    },
    {
      key: 'red-10', title: 'Hive Fall', theme: 'ashfall', size: 80, seed: 'doctrine-10',
      story: ['The Hive squats on the far side of the lava fields with every Thorn and swarm it has left. The Apex is inside.', 'The Foreman brings the whole doctrine: Bolts, Hammers, Breachers, Crushers, Mortars, and the Armoury\'s plating.'],
      briefing: 'Full war against a living Swarm: destroy the Hive.',
      epilogue: ['The Hive collapses into itself, a pyramid of dark glass. The swarms scatter and dwindle.', 'Then, from the ice, a new light: the Aegis Collective, watching, deciding.'],
      player: { faction: F, ore: 600, flux: 220 },
      enemy: fortified('blue', 'normal', { structures: [{ key: 'claim', at: 'point:5' }, { key: 'spire', at: [-5, -3] }] }),
      stages: [
        stage([obj('econ', 'capture', 'Hold 3 strategic points', { n: 3 }), obj('armory', 'build', 'Build the Armoury', { key: 'armory', n: 1 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Hive'), obj('loss', 'loseMax', 'Lose no more than 8 squads', { n: 8, optional: true })], 'Mortars on the Thorns, Hammers on the swarms, tanks on the Hive.'),
      ],
      hints: [{ at: 'start', text: 'Swarms come fast. Two Bunkers and a Hammer Team at home before you push.' }],
    },
    // ---------------- ACT III: Glass and Iron
    {
      key: 'red-11', title: 'Frozen Shields', theme: 'frost', size: 64, seed: 'doctrine-11',
      story: ['Collective Wardens on the ice, behind shields that shrug off rifle fire. The Bolts empty their magazines and the spheres do not notice.', 'The Foreman notes that shields do not care about rifles. They care about blast.'],
      briefing: 'Shields: learn to burn through Collective shields with blast and focus fire. Destroy the Warden Cells on the ice.',
      epilogue: ['Four Wardens are glass on the lake. The Collective withdraws to compute.', 'It will be back with something that shoots further.'],
      player: { faction: F, ore: 600, flux: 200, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }, { key: 'crusher', at: [5, 2] }] },
      enemy: garrison('green', { squads: [{ key: 'wardens', at: 'point:2', n: 2 }, { key: 'wardens', at: 'point:4', n: 2 }, { key: 'pulsers', at: 'point:4' }], points: [2, 4] }),
      stages: [
        stage([obj('wardens', 'kill', 'Destroy 4 Warden Cells', { key: 'wardens', n: 4 }), obj('broken', 'broken', 'Break 3 Collective squads', { n: 3 })], 'Shields recharge after three seconds without damage. Commit everything to one squad at a time.'),
        stage([obj('cap', 'capture', 'Hold 4 points', { n: 4 })]),
      ],
      hints: [{ at: 'start', text: 'The tank\'s blast ignores what the shield is made of. Bolts finish what it opens.' }],
    },
    {
      key: 'red-12', title: 'Long Sight', theme: 'crystal', size: 64, seed: 'doctrine-12',
      story: ['Lens Teams on the ridges, opening tanks from beyond rifle range. The column loses a Crusher before it sees a sphere.', 'Mortars see further than Lenses. Breachers see nothing and do not need to.'],
      briefing: 'Counter-sniping: kill the Lens Teams with Mortars and flanking Breachers, then take the Collective drill fields.',
      epilogue: ['The ridges are quiet. The drill fields belong to the Foundry.', 'The Collective has started planting Beacons. It wants to see everything.'],
      player: { faction: F, ore: 650, flux: 220, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }, { key: 'mortar', at: [5, 2] }, { key: 'breachers', at: [2, 6] }] },
      enemy: garrison('green', { structures: [{ key: 'siphon', at: 'ore:4' }, { key: 'siphon', at: 'ore:5' }, { key: 'bastion', at: 'point:3' }], squads: [{ key: 'lenses', at: 'point:3', order: 'hold' }, { key: 'lenses', at: 'point:4', order: 'hold' }, { key: 'lenses', at: 'point:5', order: 'hold' }, { key: 'wardens', at: 'point:4' }], points: [3, 4, 5] }),
      stages: [
        stage([obj('lenses', 'kill', 'Destroy 3 Lens Teams', { key: 'lenses', n: 3 }), obj('flank', 'flank', 'Land 8 flanking hits', { n: 8 })], 'Lenses die to anything that reaches them. Mortars pin, Breachers arrive from the side.'),
        stage([obj('siphons', 'destroy', 'Destroy 2 Siphons', { key: 'siphon', n: 2 }), obj('cap', 'capture', 'Hold 4 points', { n: 4 })]),
      ],
      hints: [{ at: 'start', text: 'Never march a tank straight at a Lens Team. Send it around the ridge.' }],
    },
    {
      key: 'red-13', title: 'Beacons', theme: 'urban', size: 64, seed: 'doctrine-13',
      story: ['Beacons on every point, Bastions beside them. The Collective can see the whole city, and its beams reach anything it sees.', 'The Foreman\'s answer is the oldest: shells that fall from beyond sight, and walls to hide behind while they fall.'],
      briefing: 'Vision war: destroy the Beacons and Bastions with artillery from cover, then take the points they guarded.',
      epilogue: ['The city goes blind, block by block. The Collective pulls back to its Sanctum.', 'A Sanctum is where the Collective keeps the things it does not want the Foundry to see.'],
      player: { faction: F, ore: 700, flux: 260, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }, { key: 'mortar', at: [5, 2], n: 2 }, { key: 'hammers', at: [2, 6] }] },
      enemy: garrison('green', { structures: [{ key: 'beacon', at: 'point:2' }, { key: 'beacon', at: 'point:4' }, { key: 'beacon', at: 'point:5' }, { key: 'bastion', at: 'point:4' }, { key: 'bastion', at: 'point:5' }], squads: [{ key: 'wardens', at: 'point:4' }, { key: 'pulsers', at: 'point:5' }], points: [2, 4, 5] }),
      stages: [
        stage([obj('beacons', 'destroy', 'Destroy 3 Beacons', { key: 'beacon', n: 3 }), obj('bastions', 'destroy', 'Destroy 2 Bastions', { key: 'bastion', n: 2 })]),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 }), obj('loss', 'loseMax', 'Lose no more than 3 squads', { n: 3, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Mortars outrange Bastions. Set up behind a wall and let them fall.' }],
    },
    {
      key: 'red-14', title: 'Sanctum', theme: 'ashfall', size: 64, seed: 'doctrine-14',
      story: ['The Sanctum harmonises every Collective shield on the plain, and beside it an Array is growing Nova Spheres. The Foundry has never faced a Nova. It is about to.', 'The Foreman does not intend to face one. He intends to be standing on the Array before it finishes.'],
      briefing: 'Assault: destroy the Sanctum and the Array before the Novas roll out, against a Collective that defends but does not attack.',
      epilogue: ['The Sanctum falls silent and the Array cracks open on an unfinished star.', 'The Core is next.'],
      player: { faction: F, ore: 700, flux: 280, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'crusher', at: [3, 4] }, { key: 'bolts', at: [5, 2], n: 2 }, { key: 'breachers', at: [2, 6] }, { key: 'foreman', at: [2, 2] }] },
      enemy: war('green', 'passive', { incomeMult: 1.0, structures: [{ key: 'sanctum', at: [4, -2] }, { key: 'array', at: [-4, 3] }, { key: 'bastion', at: [-3, -3] }, { key: 'bastion', at: [3, 3] }, { key: 'siphon', at: 'ore:6' }, { key: 'siphon', at: 'ore:7' }], squads: [{ key: 'wardens', at: [0, 5], n: 2 }, { key: 'nova', at: [-2, 2], order: 'hold' }, { key: 'halo', at: [3, -4] }] }),
      timeLimit: 1200,
      stages: [
        stage([obj('econ', 'capture', 'Hold 3 points', { n: 3 })]),
        stage([obj('sanctum', 'destroy', 'Destroy the Sanctum', { key: 'sanctum', n: 1 }), obj('array', 'destroy', 'Destroy the Array', { key: 'array', n: 1 })], 'Twenty minutes. Breachers on the Bastions, the tank on the Array, the Foreman beside the tank.'),
      ],
      hints: [{ at: 'start', text: 'A Nova is already on the plain. Kill it inside its minimum range or it will kill everything else.' }],
    },
    {
      key: 'red-15', title: 'Verdict', theme: 'crystal', size: 80, seed: 'doctrine-15',
      story: ['The Core sits on the dunes inside layers of Bastions, Halos and a shield that could stop the sky. The Oracle is inside, computing.', 'There is no trick left. There is only doctrine.'],
      briefing: 'Full war against a living Collective: destroy the Core.',
      epilogue: ['The shield fails. The Core cracks like an egg. The Oracle\'s light goes out across the sand.', 'In the west the Hive stirs again, and this time the Collective\'s survivors stir with it.'],
      player: { faction: F, ore: 650, flux: 240 },
      enemy: fortified('green', 'normal', { incomeMult: 1.15, structures: [{ key: 'beacon', at: 'point:5' }, { key: 'sanctum', at: [-5, -3] }] }),
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('mortar', 'train', 'Field 2 Mortar Blocks', { key: 'mortar', n: 2 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Core'), obj('loss', 'loseMax', 'Lose no more than 10 squads', { n: 10, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Energy weapons shred vehicles. Screen your tanks with Bolts and keep the Foreman near the armour.' }],
    },
    // ---------------- ACT IV: The Coalition
    {
      key: 'red-16', title: 'Two Fronts', theme: 'verdant', size: 64, seed: 'doctrine-16',
      story: ['Swarm Thorns and Collective Bastions on the same ridge. The old enemies have decided the Foundry is the newer problem.', 'The Foreman finds this reasonable. He would have done the same.'],
      briefing: 'Mixed garrison: clear a ridge held by both Swarm and Collective forces and take every point on it.',
      epilogue: ['The ridge falls. The two garrisons never learned to fight together, only to die together.', 'Both remaining strongholds are now sending everything they have.'],
      player: { faction: F, ore: 650, flux: 240, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }, { key: 'hammers', at: [5, 2] }, { key: 'crusher', at: [2, 6] }] },
      enemies: [garrison('blue', { structures: [{ key: 'thorn', at: 'point:2' }, { key: 'claim', at: 'point:2' }], squads: [{ key: 'darts', at: 'point:2', n: 2 }, { key: 'needles', at: 'point:2' }], points: [2] }), garrison('green', { structures: [{ key: 'bastion', at: 'point:4' }, { key: 'beacon', at: 'point:4' }], squads: [{ key: 'wardens', at: 'point:4' }, { key: 'lenses', at: 'point:4' }], points: [4] })],
      stages: [
        stage([obj('kill', 'kill', 'Destroy 5 enemy squads', { n: 5 }), obj('posts', 'destroy', 'Destroy the Claim Spike and the Beacon', { n: 2 })]),
        stage([obj('cap', 'capture', 'Hold 5 points', { n: 5 })]),
      ],
      hints: [{ at: 'start', text: 'Hammers for the swarms, the tank for the shields. Never both at once.' }],
    },
    {
      key: 'red-17', title: 'Siege of the Works', theme: 'urban', size: 80, seed: 'doctrine-17',
      story: ['The coalition attacks from both corners of the city at once, waves timed to arrive together, with Kites over the roofs and Novas behind.', 'The Foundry has an Iron Works, four points and eight minutes to remind everyone what it is for.'],
      briefing: 'Two-front defence: hold four points for eight minutes against alternating Swarm and Collective waves.',
      epilogue: ['The city is quiet and the streets are full of triangles and spheres.', 'Their economies are exposed. The Foreman intends to make that permanent.'],
      player: { faction: F, ore: 750, flux: 300, structures: [{ key: 'works', at: [-4, 3] }, { key: 'bunker', at: [6, 1] }, { key: 'bunker', at: [-6, -1] }], squads: [{ key: 'bolts', at: [3, 4], n: 2 }, { key: 'hammers', at: [5, 2], n: 2 }, { key: 'foreman', at: [2, 2] }], points: [0, 1, 2, 3] },
      enemies: [garrison('blue', { points: [4] }), garrison('green', { points: [5] })],
      waves: [wave(60, [{ key: 'darts', n: 3 }], { owner: 1, text: 'Swarm from the north.' }), wave(120, [{ key: 'wardens', n: 2 }], { owner: 2, text: 'Wardens from the south.' }), wave(200, [{ key: 'kites', n: 2 }, { key: 'wedges', n: 1 }], { owner: 1, text: 'Kites and Wedges.' }), wave(280, [{ key: 'pulsers', n: 2 }, { key: 'lenses', n: 1 }], { owner: 2, text: 'Pulse Rings and a Lens Team.' }), wave(360, [{ key: 'obelisk', n: 1 }, { key: 'darts', n: 2 }], { owner: 1, text: 'An Obelisk.' }), wave(430, [{ key: 'nova', n: 1 }, { key: 'halo', n: 1 }, { key: 'wardens', n: 1 }], { owner: 2, text: 'A Nova with a Halo.' })],
      stages: [
        stage([obj('hold', 'hold', 'Hold 4 points for 8 minutes', { n: 4, seconds: 480 }), obj('loss', 'loseMax', 'Lose no more than 4 squads', { n: 4, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'Mortars behind the Bunkers reach the Obelisk and the Nova before they reach you.' }],
    },
    {
      key: 'red-18', title: 'Rail Raid', theme: 'ashfall', size: 80, seed: 'doctrine-18',
      story: ['Lode Burrows and Siphons share the lava fields, guarded by Thorns and Bastions. Two economies feeding two enemies.', 'The Foreman sends the tanks with one instruction: nothing that pumps ore is to be left standing.'],
      briefing: 'Deep raid: destroy the extractors of both enemies without losing more than two squads.',
      epilogue: ['The lava fields are dark. Two economies starve at once.', 'Only the Hive stands between the Foundry and the Prime Vein.'],
      player: { faction: F, ore: 700, flux: 300, structures: [{ key: 'works', at: [-4, 3] }], squads: [{ key: 'crusher', at: [3, 4], n: 2 }, { key: 'bolts', at: [5, 2], n: 2 }, { key: 'foreman', at: [2, 2] }] },
      enemies: [war('blue', 'passive', { incomeMult: 0.9, structures: [{ key: 'lode', at: 'ore:6' }, { key: 'lode', at: 'ore:4' }, { key: 'thorn', at: 'ore:4' }], squads: [{ key: 'darts', at: 'ore:6' }] }), war('green', 'passive', { incomeMult: 0.9, structures: [{ key: 'siphon', at: 'ore:7' }, { key: 'siphon', at: 'ore:5' }, { key: 'bastion', at: 'ore:5' }], squads: [{ key: 'lenses', at: 'ore:7' }] })],
      stages: [
        stage([obj('lodes', 'destroy', 'Destroy 2 Lode Burrows', { key: 'lode', n: 2 }), obj('siphons', 'destroy', 'Destroy 2 Siphons', { key: 'siphon', n: 2 }), obj('loss', 'loseMax', 'Lose no more than 2 squads', { n: 2 })]),
      ],
      hints: [{ at: 'start', text: 'Both enemies rebuild. Hit fast, leave, and come back for what they rebuild.' }],
    },
    {
      key: 'red-19', title: 'The Breaking', theme: 'frost', size: 80, seed: 'doctrine-19',
      story: ['The Hive has rebuilt on the ice with Collective Bastions at its gates and Halos over its swarms. It has learned everything.', 'So has the Foreman.'],
      briefing: 'Full war against a hardened Swarm with Collective support: destroy the Hive.',
      epilogue: ['The Hive falls for the second and last time. The Collective garrison surrenders the gates.', 'Beyond the ice the Prime Vein hums, and every faction that is left is marching toward it.'],
      player: { faction: F, ore: 700, flux: 280 },
      enemies: [fortified('blue', 'hard', { incomeMult: 1.15, structures: [{ key: 'spire', at: [-5, -3] }, { key: 'claim', at: 'point:5' }] }), garrison('green', { structures: [{ key: 'bastion', at: 'point:4' }, { key: 'beacon', at: 'point:4' }], squads: [{ key: 'wardens', at: 'point:4' }, { key: 'halo', at: 'point:4' }], points: [4] })],
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('armory', 'build', 'Build the Armoury', { key: 'armory', n: 1 })]),
        stage([obj('hq', 'destroyHq', 'Destroy the Hive'), obj('loss', 'loseMax', 'Lose no more than 10 squads', { n: 10, optional: true })]),
      ],
      hints: [{ at: 'start', text: 'The hard Swarm rushes early. Two Bunkers and two Hammer Teams before anything else.' }],
    },
    // ---------------- FINALE
    {
      key: 'red-20', title: 'Prime Vein', theme: 'crystal', size: 80, seed: 'doctrine-20',
      story: ['The Prime Vein lies open under the dunes, and around it, in three corners of the world, three peoples have built everything they have left.', 'The Swarm and the Collective will fight each other as readily as the Foundry. The Foreman does not mind. The Foundry has always been the last thing standing, because it is the only one that was built to stand.'],
      briefing: 'All-out war: two living enemies, both hard, on the largest battleground. Destroy both the Hive and the Core.',
      epilogue: ['The Hive falls. The Core falls. The Prime Vein lies in the open and the Foundry begins, immediately, to build.', 'The Lattice will be reforged, in the shape that lasts. Campaign complete.'],
      player: { faction: F, ore: 800, flux: 320 },
      enemies: [fortified('blue', 'hard', { incomeMult: 1.2, structures: [{ key: 'spire', at: [-5, -3] }] }), fortified('green', 'hard', { incomeMult: 1.2, points: [], structures: [{ key: 'sanctum', at: [-5, -3] }] })],
      stages: [
        stage([obj('econ', 'capture', 'Hold 4 strategic points', { n: 4 }), obj('hero', 'hero', 'Field the Foreman')]),
        stage([obj('hqs', 'destroyHq', 'Destroy the Hive and the Core', { all: true }), obj('loss', 'loseMax', 'Lose no more than 15 squads', { n: 15, optional: true })], 'They will fight each other. Let them, then finish whoever wins.'),
      ],
      hints: [{ at: 'start', text: 'Three-way war: the two enemies attack each other too. Hold your corner, harvest, and strike the weaker one first.' }],
    },
  ],
};
